### ISSUE TITLE
Account window has no back button

### ISSUE THREAD

**Issue by leee** [thedillonb/CodeHub#101]
![](http://i.imgur.com/mMa2qxu.jpg)

After clicking the Account button displayed above, it is impossible to go back afterwards to the menu, thereby forcing users to close the application to get back as demonstrated below. 

![](http://i.imgur.com/xiAPmUP.jpg)

Otherwise, amazing work! I love CodeHub (and if it weren't for the fact that I was a broke college student, would pay for the paid version).

**Comment by thedillonb** [comment]
![Back](http://g.recordit.co/j0T4ZgefRM.gif) Added a "cancel" button when in the account screen so you can back out of chaging an account. Likewise, you can just tap your name again.
