### ISSUE TITLE
Repo doesn't build

### ISSUE THREAD

**Issue by zgramana** [thedillonb/CodeHub#106]
Even after 60cf8bc81b8c30a91993d8063499e7559166eed5#diff-d41d8cd98f00b204e9800998ecf8427e, which definitely improved things, I'm still unable to successfully build and run.

I can now build, but TinyIoC doesn't get view models registered and throws an exception during app launch. It looked like it was perhaps grabbing a stale Xamarin Utilities assembly, but didn't have time to really dig into it very far.

We'd love to get it usable so we can play with it and maybe send you some PRs. : )

**Comment by thedillonb** [comment]
This issue has been resolved. I got rid of the Xamarin.Utilities project and just collapsed it into the CodeHub project. All other dependencies are NuGet'ed. The project should build just fine now.
