### ISSUE TITLE
Use Octicons instead of custom image icons

### ISSUE THREAD

**Issue by davidcelis** [thedillonb/CodeHub#108]
To improve the look and feel of CodeHub, you could use GitHub's [Octicons font](https://octicons.github.com) now that they've released it for public use. Using the icons that github.com itself uses would help CodeHub feel more like a native GitHub experience.

**Comment by thedillonb** [comment]
Next version will use the Octicons!

![ios simulator screen shot feb 7 2015 3 03 16 pm](https://cloud.githubusercontent.com/assets/1644068/6093744/792933b0-aeda-11e4-988e-1cd4f063e265.png)
![ios simulator screen shot feb 7 2015 3 03 13 pm](https://cloud.githubusercontent.com/assets/1644068/6093745/792a4b74-aeda-11e4-9cfc-a15752de2065.png)


Future verisons will even have a theme editor so people can create different types of icons/themes for the app!
