### ISSUE TITLE
Feature Request: Please add "releases" and "download_count" to codehub

### ISSUE THREAD

**Issue by dbcb** [thedillonb/CodeHub#109]
First, thanks for the great app.
I miss the information about releases and the download count in codehub.
Since this information is only available over the API, it would be great if codehub can add it.

**Comment by thedillonb** [comment]
Added release information in the next version:

![Release](http://g.recordit.co/sr0hhlePUN.gif)

As for downloads, per the GitHub documents:

> The Downloads API (described below) was deprecated on December 11, 2012. It will be removed at a future date. We recommend using Releases instead.

Downloads is being replaced by `Releases`

**Comment by crimoniv** [comment]
Sorry for bumping, but I don't find `Releases` button or another similar one in the latest **App Store** version (2.18.1.2) under iOS 10.3.3. Has it been replaced or moved to another screen?

Thanks in advance!
