### ISSUE TITLE
View Accounts pages,no back menu.

### ISSUE THREAD

**Issue by jptiancai** [thedillonb/CodeHub#113]
when click `Account page`,no menu button.
Then if I want to back the home page,just relogin in or reopen the app?

**Comment by thedillonb** [comment]
If you're in the account page you can simply just click on your account again to get back to the menu.

Either way, I have added a "back" button in the next version:

![Back](http://g.recordit.co/j0T4ZgefRM.gif)

**Comment by CodeMan99** [comment]
Came here to report this issue. Glad to see it's already covered, but when will this bug be in a release, @thedillonb? The app page is reporting version "2.3.3", but I don't see that release on github.

**Comment by jptiancai** [comment]
@thedillonb  Glad to see the issue solved. :+1:
