### ISSUE TITLE
Organisations event view

### ISSUE THREAD

**Issue by JohanvdWest** [thedillonb/CodeHub#114]
It would be great if the events page of an organisation shows the events of all repositories owned by that organisation.

Makes for a nice overview of what is happening in the code, even your own commits and issues.

**Comment by thedillonb** [comment]
The organization event view currently shows events for all repositories and resources owned by that organization. E.g:

![screen shot 2016-04-02 at 10 29 43 pm](https://cloud.githubusercontent.com/assets/1644068/14230390/994902ae-f922-11e5-8ed8-a1951c593467.png)
