### ISSUE TITLE
Feature Request: Create a new file!?

### ISSUE THREAD

**Issue by AndrewFreemantle** [thedillonb/CodeHub#116]
I may be missing the obvious, as I can edit an existing file within a GitHub hosted project, but how can I add a new file using CodeHub?

I'm thinking this would be **really** handy for uploading blog posts to a Jekyll hosted site on GitHub Pages..  ;o)

**Comment by thedillonb** [comment]
Consider it done http://g.recordit.co/q5qs0Z1fLL.gif

It will be in the next release.

**Comment by AndrewFreemantle** [comment]
Nice, and thanks for the .gif too  :smiley:
