### ISSUE TITLE
Extra line breaks when viewing file

### ISSUE THREAD

**Issue by ecnepsnai** [thedillonb/CodeHub#118]
When viewing a file there are blank lines added every other line, these lines aren't in the actual file and only show up on codehub.

Here's an example of what I mean, all of these extra blank lines aren't actually in my source file.

![2015-01-05 10 56 35](https://cloud.githubusercontent.com/assets/1607109/5618057/cb91c4ee-94c9-11e4-9f98-1f62886c1278.png)

The actual file looks like:

    require 'sinatra'
    require 'json'
    require 'curl'
    require 'time_difference'

    class Timetable

I'm using an iPhone 5S, 8.1.1, CodeHub 2.3.3

**Comment by thedillonb** [comment]
Resolved in the next release. This was an issue of line-endings. Obviously some are just '\n' and some '\r\n' so CodeHub now accounts for both.

![ios simulator screen shot feb 7 2015 3 13 35 pm](https://cloud.githubusercontent.com/assets/1644068/6093769/e9a81be6-aedb-11e4-8f0a-20a715382fa8.png)

**Comment by ecnepsnai** [comment]
Good to hear, thanks for fixing this!
