### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by thorade** [thedillonb/CodeHub#120]
Just a question: 
I would love to use CodeHub on Android. 
Is there any chance you are going to make it available there, too?
Searching your repo for Android makes me hope so
https://github.com/thedillonb/CodeHub/search?utf8=%E2%9C%93&q=android

**Comment by Shawzborne** [comment]
Yes he is adding it to android

**Comment by thorade** [comment]
Awesome! Looking forward to that.
So I'll just follow https://twitter.com/CodeHubApp
and this issue here can be closed.
