### ISSUE TITLE
Issues with Github Enterprise

### ISSUE THREAD

**Issue by wackyMole** [thedillonb/CodeHub#125]
When setting up a Github Enterprise account, after entering your domain and username and prompted for the password, the input box scrolls off the top of the screen.

Also, potentially another issue, if Two-Factor authentication is enabled on the Github Enterprise account, The app throws an error saying "The request was unable to be processed due to an interal server error."

**Comment by thedillonb** [comment]
@wackyMole, whoa, that's a new one. Just so I understand correctly, your GitHub Enterprise account has Two-Factor authentication enabled and when you get prompted to enter in the code it scrolls off the top of the screen? Do you happen to know what the version of the GitHub Enterprise instance is that you're connecting to?

**Comment by wackyMole** [comment]
@thedillonb Well not exactly. :) the scrolling hapens when I'm prompted for a password. I'm never prompted for the two factor auth code.

Steps to reproduce:
1) Go to accounts and tap the "+" to add a new account.
2) Tap the box for "Enterprise".
3) Tap the "Domain" input box. At this point all of the others disappear.
4) Enter my Github Enterprise domain ("github.mydomain.com").
5) Tap "Next". The screen slides up slightly and the "Username" input box re-appears.
6) Enter my Github Enterprise username. ("wacky.mole")
7) Tap "next". All content scrolls off of the top of the screen but the keyboard remains.
8) At this point I can still enter something. So I enter my password and tap "Go"
9) All of the content scrolls back down onto the screen and after a second or so, I get an alert saying "The request was unable to be processed due to an interal server error." (Misspelling intentional)

At this point if I hit "OK" and tap on the "Password" input field again the input fields remain in place though the Github graphic is still of the screen.

Now if I hit the left arrow a couple times to go back to e accounts screen. I have two new accounts that show up. (Neither works)

Note that domains and usernames are changed but adhere to the actual format of each in case that info helps in troubleshooting. I'm not 100% positive but I believe we are running version 2.1 of Github Enterprise. The internal team that supports that system is planning to upgrade to 2.2 within a few days. I'll test it there as well. My phone is running IOS 8.3 on iPhone 6 but I know the problem existed on 8.2 as well. (If that helps)

**Comment by wackyMole** [comment]
@thedillonb Also (and this may be a separate issue) if I disable TFA on Github Enterprise and then try to set up the account, the same thing happens up until step 9. Instead of step 9, everything works and I can log in. But if I go back to the accounts screen, I can't delete the Github Enterprise accounts. If I slide to delete them, almost instantly, the delete button disappears and the entry slides back to its original position.

**Comment by wackyMole** [comment]
Doesn't work in GHE 2.2.1 either.

**Comment by thedillonb** [comment]
hey @wackyMole, damn, you're absolutely right. There's a bunch of screwy things happening in the app. Fortunately, I've managed to fix them in the next version (3.0) which I'm hoping on finishing up in the upcoming week. The downside is that, as you mentioned, the app is currently a disaster in landscape mode. I dunno what happened with 2FA. I must of some how screwed it up in the last release as I've been trying to move off a custom GitHub client to their official one - although, 2FA is definitely one of the features I try to test before the app releases. 

Regardless, look for 3.0 soon. It should solve the landscape issue, the 2FA issue, and the fact that it seems to deny you the act of actually deleting your account..

**Comment by wackyMole** [comment]
Any update on this?

**Comment by jvanbrug** [comment]
I don't see any layout/scroll problems, but I have to disable 2FA to use the app - would love to see a fix so I can re-enable 2FA!

**Comment by jvanbrug** [comment]
I got 2FA to work by generating a personal access token and logging in to CodeHub with username=`x-oauth-basic` and password=token

**Comment by thedillonb** [comment]
@jvanbrug, very clever! Never thought of that. I'm working on making "personal access tokens" a login flow so you fall back to that natively if 2FA doesn't work. I've always had a hard time getting 2FA working consistently as I don't personally have access to a GitHub Enterprise account so I basically beg GitHub to give me a trial version which ends up expiring after a month. So that process is a bit tiring which results in test case holes around 2FA and GitHub Enterprise. Regardless, I'll make sure it gets fixed!

**Comment by jvanbrug** [comment]
@thedillonb thanks for all the work! I really enjoy the app. :smiley:

**Comment by thedillonb** [comment]
I've just put the fix in for 2FA into the master branch. I'll cut the release ASAP for the app store. I'll get started on the personal token feature and have that in the following version. I've opened another ticket #171 to track the work for personal tokens.
