### ISSUE TITLE
Crashes on iOS 9 Immediately

### ISSUE THREAD

**Issue by kanyonbollinger** [thedillonb/CodeHub#129]
Upon opening the app, CodeHub crashes immediately.

**Comment by Mikoj** [comment]
+1

**Comment by thedillonb** [comment]
Thank's for pointing this out. It probably requires a re-compile for iOS 9 - I wasn't even aware iOS 9 was available yet.

**Comment by kanyonbollinger** [comment]
It's still in beta. I'm just letting you know ahead of time.

**Comment by Menshawi** [comment]
Confirming this too, it crashes immediately on IOS9. Tested on iphone 6

**Comment by robertybob** [comment]
As above , public beta of iOS 9 and it's crashing immediately upon launch.

**Comment by Aahung** [comment]
According to http://developer.xamarin.com/guides/ios/platform_features/ios9/
> To ensure your existing Xamarin.iOS apps run smoothly on iOS 9, download the latest Xamarin.iOS release (8.10.3.2) from our Stable channel (or if you have the previously released 8.10.1.74 that will also work) (release info) then re-build and re-deploy your apps using Xcode 6 on OS X Yosemite.

**Comment by Menshawi** [comment]
why isn't anyone taking care of this already?

**Comment by kanyonbollinger** [comment]
To be fair, iOS 9 isn't officially released yet. However, other apps don't crash on iOS 9 which means it's not iOS 9 related. I've seen other companies push out fixes for iOS 9 - they just don't say it's an iOS 9 fix in the update description.

**Comment by mfwass** [comment]
"To be fair, iOS 9 isn't officially released yet"

The beta has been out for months, the app should work on it by now. There is also a public beta, making the software even more popular on devices. It should be a top priority to fix this issue due to the sheer number of how many users have iOS 9. I have not had any issues with other apps on my iPhone. This is isolated to CodeHub.

**Comment by thedillonb** [comment]
@mfwass, I appreciate your enthusiasm for seeing CodeHub on iOS 9! I am currently finishing up the next version of the app which supports iOS 9. However, I am extremely cautious about releasing it before the beta has ended. The number of times I've seen oddities occur from beta to RTM is quite numerous - when iOS 7 and 8 came out there was a lot of this. I want to make sure when I release the version it doesn't operate unexpectedly just because Apple, or Xamarin, altered something from beta to RTM.

**Comment by mfwass** [comment]
@thedillonb A faulty running program would be better than one running not at all. Those who download the iOS 9 Beta understand that things may not work as expected, including CodeHub. If you know of a potential fix, throw it up there. Us *beta* testers will do our job as *beta* testers and report the bugs.

**Comment by Aahung** [comment]
Yep I understood and it is indeed not mandatory to make compatible for iOS 9 during the beta phase. While on the other hand, if it matters only to recompile with newer version of Xamarin, I think it is worth doing. 
In addition, it does not require Xcode 7 beta so you are still using the stable compiler to build the CodeHub:
> Apple recently released iOS 9 and announced a public preview will start in July 2015. Follow the instructions on this page to ensure your existing apps (built with your existing Xcode 6 installation) will run on iOS 9. 
> To ensure your existing Xamarin.iOS apps run smoothly on iOS 9, download the latest Xamarin.iOS release (8.10.3.2) from our Stable channel (or if you have the previously released 8.10.1.74 that will also work) (release info) then re-build and re-deploy your apps using Xcode 6 on OS X Yosemite.
> This will allow your existing apps to run in iOS 9 previews, and be ready for the fall release of iOS 9 (https://developer.xamarin.com/guides/ios/platform_features/ios9/)

So in conclusion, it won't be risky and I really hope you can do it and submit new version to App Store before iOS 9 official launch sooner in September. There is also around 6 to 7 days for reviewer to review the submission, during the official launch to the "ready for sale" day, users with iOS 9 upgraded will have no CodeHub to use.

**Comment by thedillonb** [comment]
@mfwass & @Aahung, after thinking about this a little more, you guys are right. I will start the app approval process on Apple's side and get the upgraded version out the door. Thanks again for being so enthusiastic about seeing CodeHub on iOS9.

**Comment by Aahung** [comment]
@thedillonb That would be great! Should still be 19 days until launching, time is enough for reviewing. Better CodeHub with you nice developers.

**Comment by mfwass** [comment]
@thedillonb Wonderful! I look forward to being able to test CodeHub on iOS 9, if I come across any issues I'll be sure to report them. Thank you. :+1:

**Comment by thedillonb** [comment]
You guys will be happy to know, that after 14 days, Apple has finally reviewed the App and it is now processing for the App Store! It should be in your hands very soon!

**Comment by kanyonbollinger** [comment]
@thedillonb Thank you!!

**Comment by mfwass** [comment]
Wonderful! I look forward to getting the update notification.

**Comment by mfwass** [comment]
![image](https://cloud.githubusercontent.com/assets/8769835/9958586/83116362-5dd9-11e5-8677-668e10ace533.jpeg)
hype
