### ISSUE TITLE
How can I build xamain.ios in only one computer

### ISSUE THREAD

**Issue by lipangit** [thedillonb/CodeHub#136]
I install windows system in my mac, and install vs 2015 in windows,  I run this project but vs let me connect to Xamarin.ios build host, I have only one computer,How can I build this project.

**Comment by thedillonb** [comment]
I typically just build this on my mac. You just need Xamarin.iOS for Mac and you're able to build this project. No windows needed.

**Comment by lipangit** [comment]
Yes!!  I take a roundabout course。

**Comment by lipangit** [comment]
I use Xamarin.iOS for Mac run a sample , but I did not open Xamarin.iOS Build host, does it useful for mac
