### ISSUE TITLE
Error while logging in first time

### ISSUE THREAD

**Issue by naveensrinivasan** [thedillonb/CodeHub#139]
Here is the screen shot of the error when I was trying to login first time
![img_8786](https://cloud.githubusercontent.com/assets/172697/9701409/3ce41a9e-53f5-11e5-8a4e-a7b5ec15ed79.PNG)

**Comment by thedillonb** [comment]
@naveensrinivasan, yeah that all of a sudden started a while ago. While annoying, it's harmless and if you click "Ok" you can proceed on without issue. This will definitely be fixed in the next version. Thank's for pointing it out though!

**Comment by naveensrinivasan** [comment]
I did that. Just wanted to make sure it was reported.Thanks!
