### ISSUE TITLE
_UIAHandler.py in NVDA repo is shown with incorrect syntax highlighting

### ISSUE THREAD

**Issue by vasily-v-ryabov** [thedillonb/CodeHub#147]
I'm viewing this file on iOS 8.4 (CodeHub 2.3.7): https://github.com/ckundo/nvda/blob/master/source/_UIAHandler.py

Incorrect syntax highlighting starts from line 3.
![codehub_bug_nvda](https://cloud.githubusercontent.com/assets/7419086/10756436/314f2e42-7cb5-11e5-8501-bebbc2a743fb.JPG)

**Comment by thedillonb** [comment]
Yeah, unfortunately the parser I used in the app (highlight.js) does not always do the correct thing. I'm not really sure why it does what it does, but I plan on replacing it in the very near future.

**Comment by thedillonb** [comment]
I've implemented a new syntax highlighter in the next version 2.5.0 - which Apple is reviewing now.

![screen shot 2016-02-07 at 12 30 35 am](https://cloud.githubusercontent.com/assets/1644068/12871023/251ab6c8-cd32-11e5-9a46-829a9cf3d843.png)

**Comment by vasily-v-ryabov** [comment]
It works fine in 2.6.0. Thanks! :+1:
