### ISSUE TITLE
"Error! Unable to save labels! Please try again." for organization repo issue

### ISSUE THREAD

**Issue by vasily-v-ryabov** [thedillonb/CodeHub#148]
I'm trying to add label "bug" for the issue in my own organization repo. But after pressing "Back" arrow CodeHub shows some progress and then error message listed above.

**Comment by thedillonb** [comment]
Interesting. I'll take a look into this. Is this a repository you own in the organization or is it owned by others? If the latter, do you have permissions to edit labels in the browser?

**Comment by vasily-v-ryabov** [comment]
Of course, I have permissions to change labels because I'm an owner of [the organization](https://github.com/pywinauto).

**Comment by thedillonb** [comment]
Hmm, I'm not sure why that might be. The label I just added to this ticket was done using CodeHub so I'm not sure where that would come from if you owned the repository, or was given collaborator status. I keep trying to investigate.

**Comment by vasily-v-ryabov** [comment]
Some time ago I subscribed to early access program for new access rights customization for organizations. If this early access program is not deployed yet for everyone, that might be a root cause.

BTW, our organization has no "Owners" group, but I'm an owner. Also I'm explicitly a member of "Contributors" group that has write access to each repo in the organization. Hope it makes the situation more clear.

**Comment by vasily-v-ryabov** [comment]
This is working with disabled "Restricted access" for third-party access settings. Thanks!
