### ISSUE TITLE
List Forks

### ISSUE THREAD

**Issue by Nerdpie** [thedillonb/CodeHub#152]
Using the app on my iPhone, I would like to be able to see the list of forks, in addition to the number of forks.  For instance, Minecraft mods are sometimes no longer developed by the original dev, and being able to see if any forks are active is very useful.

I do not know what data is exposed by the APIs, and I imagine that a full network graph would be a pain on mobile, but any work on this would be appreciated.

**Comment by thedillonb** [comment]
Some preliminary support for listing forks will be in the next release:

![Forks](http://g.recordit.co/hvPpDvIIgL.gif)
