### ISSUE TITLE
Can't see issue comments and crash when opening readme

### ISSUE THREAD

**Issue by negebauer** [thedillonb/CodeHub#154]
When you open an issue you can't read neither the description and neither the comments of the issue

Also, when you open the readme of a repo the app crashes

Currently at v2.5.0 (2.5.0.1)

(Btw, the ui looks much cooler now 👍🏻)

**Comment by negebauer** [comment]
Here is an image of the issue problem I mentioned

![](http://i.imgur.com/ZX6f4Tg.jpg)

**Comment by negebauer** [comment]
Also, issue take way longer to load the info to display and sometimes it just doesn't load at all

**Comment by thedillonb** [comment]
Hey @negebauer, I don't know how this happened but for some reason in this past release a menu image and the markdown resources (which are used to produce the readme and issue comments/description) are completely missing from the bundle that was sent to Apple. This is what is causing the crash in the Readme and the lack of loading in the issues.

This has been the first time assets have gone missing but greatly shakes my faith in Xamarin to produce iOS bundles. I, unfortunately, cannot test App Store signed bundles on my phone so I have to take it on faith they were constructed well - which as we can see, were not.

I apologize for this inconvenience and am asking Apple to expedite the release of the next version to fix this problem.

**Comment by negebauer** [comment]
@thedillonb well that's unfortunate and weird, hope it doesn't happen in the next version!

**Comment by thedillonb** [comment]
Yeah me too :( Apple is currently reviewing the next version now. Luckily, they've agreed to expedite the review process so this will hopefully be solved very very soon.

**Comment by thedillonb** [comment]
@negebauer, latest version in the App store resolves this... Jeez that sucked. Thanks for your quick feedback!

**Comment by negebauer** [comment]
@thedillonb, it's working like a charm again
With such a quick fix we can pretend this never happened
