### ISSUE TITLE
Crashes when trying to view READMEs

### ISSUE THREAD

**Issue by rohan-deshpande** [thedillonb/CodeHub#155]
Using `2.5.0.1` on iOS 9.2, not sure why this suddenly started happening, was fine yesterday.

**Comment by thedillonb** [comment]
@rohan-deshpande, are you up to date with the latest version? It should be 2.5.1.1. There was an issue with the bundle (2.5.0.1) that was published which caused the crash that has been resolved since.

**Comment by rohan-deshpande** [comment]
Yeah I'm on 2.5.1.1 now and it's fixed. Thanks!
