### ISSUE TITLE
Organisations Setting reversed

### ISSUE THREAD

**Issue by farmio** [thedillonb/CodeHub#156]
In Settings when the "List Organisazions in Menu" toggle is turned on the Organisations Menu Item is hidden and vice versa. Shouldn't it be the other way around?

**Comment by thedillonb** [comment]
The "List Organizations" option will list every organization you belong to individually in the slide-out menu. With it disabled, you should only see a single mention option: "Organizations". If "List Organizations" is enabled but you don't see anything, then you're probably hitting a common issue where the organizations you belong to have [3rd Party Access disabled](https://help.github.com/articles/about-third-party-application-restrictions/). When 3rd Party Access is disabled it will not report you as belonging to the Organization which means CodeHub will not display it on the slide-out menu. 

Let me know if that helps

**Comment by farmio** [comment]
Ah thank you for the clarification!
