### ISSUE TITLE
watcher cound not displayed correctly.

### ISSUE THREAD

**Issue by sharpner** [thedillonb/CodeHub#158]
In the app the watcher count always equals the stars count:

![img_0582](https://cloud.githubusercontent.com/assets/574362/13153486/b1ed51f0-d674-11e5-9607-9cade4725238.JPG)

**Comment by thedillonb** [comment]
@sharpner, lol, damnit! I must have wired up the wrong counter when I changed the UI and not noticed that correlation. I'll fix this in the next release. Thanks for the heads up.

**Comment by sharpner** [comment]
:D yeah I figured that it would just be a copy paste mistake :P

**Comment by thedillonb** [comment]
Fixed in the latest version (2.6.0) which has been released to the AppStore just this moment :) You should see the update soon!
