### ISSUE TITLE
Edit gist not working for me

### ISSUE THREAD

**Issue by dsyer** [thedillonb/CodeHub#159]
I can see the edit function, but when I make a change and save it, the change is not appearing in the gist when I open it again.

**Comment by dsyer** [comment]
Actually, it does work, but you have to press the "Save" icon twice (kind of non obvious).

**Comment by dsyer** [comment]
There's more though. I can only edit about a page of any gist (the first 40 lines or so). The rest never shows up in the editor. So the summary of this issue is correct but the description is not (it would be nice to be able to edit it).

**Comment by thedillonb** [comment]
@dsyer, very interesting. I will look into this ASAP. I think I may have fixed the two issues you mention above (the fact that the file is not sync'ed when you save and the fact you have to hit save twice). But, I haven't seen the latter issue yet. I'll try to reproduce it and fix it. Thanks for reporting this.

**Comment by thedillonb** [comment]
I've resolved the 40 line issue. I'm not sure how that happened but it will be fixed in the next version.

![example](http://g.recordit.co/8dorEyCyrB.gif)
