### ISSUE TITLE
Share menu on repo page

### ISSUE THREAD

**Issue by kiliankoe** [thedillonb/CodeHub#161]
Hi, I'd love it if it were possible to share the link to a repo right from the main view. Currently this doesn't seem to be possible, so I'm resorting to going to the README instead and sharing a link to that.

Thanks for considering! :)

**Comment by thedillonb** [comment]
@kiliankoe, wow, good point. Seems silly that the repo view doesn't have a share! I can definitely make that happen! Thanks for the feedback.

**Comment by norcross** [comment]
Wanted to chime in and say this would be very helpful for me as well (I think it's the same thing). Screenshot of the area that the link would help in.

![codehub- slideout](https://cloud.githubusercontent.com/assets/98561/13709250/edf98354-e780-11e5-96a5-dce1a39e4156.png)

**Comment by helsinglee** [comment]
dark/light theme can only switch one time.
