### ISSUE TITLE
Cryptographically validate app code?

### ISSUE THREAD

**Issue by jabbett** [thedillonb/CodeHub#163]
I work with paranoid security people. How do I prove to them that the open-source code you host here is the code that's available for download in the App Store? Thanks.

**Comment by thedillonb** [comment]
Haha that's a good question. Let me ponder that a little bit and see if I can't find a way to definitively prove that they are the same.

**Comment by thedillonb** [comment]
@jabbett, I can't think of any good way to prove this. Do you know of any other apps that might provide such a feature - maybe I can reverse engineer how they're doing it.

**Comment by thedillonb** [comment]
Unfortunately, I cannot think of a mechanism to fulfill this request. It's not that I purposefully change code locally but a post-deploy step is to actually fill in secret API keys necessary for the operation of the app. Just that technically diverges the code from what's checked-in here and thus, invalidates any chance of me somehow creating a cryptographically hash to prove code equality.

I'm closing this but will keep my eye open for anyone else whom may have found a way to rectify this.
