### ISSUE TITLE
Give error when commiting files but actually succeed

### ISSUE THREAD

**Issue by FiveYellowMice** [thedillonb/CodeHub#164]
The app gives the following error every time when commiting changes of a text file.

![image](https://cloud.githubusercontent.com/assets/9077203/13446053/6e3c49a8-e064-11e5-80c8-853dffa93891.jpeg)

But the commit actually succeed.

**Comment by thedillonb** [comment]
Interesting... I'll take a look at it

**Comment by thedillonb** [comment]
@FiveYellowMice, does this happen on every file you edit? Does the file belong to a repository that is owned by an organization? I cannot seem to reproduce this no matter how I try:

![img](http://g.recordit.co/zOPzm9jIA7.gif)

**Comment by FiveYellowMice** [comment]
Well, it keeps happening on every text file in my repository, until I uninstall and reinstall the app. And I can not reproduce it now either. So it'll be fine...
