### ISSUE TITLE
Notifications showing twice

### ISSUE THREAD

**Issue by negebauer** [thedillonb/CodeHub#167]
In my iOS app everytime I receive a notification it arrives duplicated.

**Comment by negebauer** [comment]
This is basically what happens:

![](http://i.imgur.com/ovgK0Ek.jpg)
![](http://i.imgur.com/Vt1rd6o.jpg)

**Comment by thedillonb** [comment]
@negebauer whoa. That's a new one. I wonder if something happened during registration where it registered you twice. I will look into it ASAP. I assume this is happening for the "negebauer" user?

**Comment by negebauer** [comment]
@thedillonb Yes! for the @negebauer user
It's been happening for, well, ever since I got notifications

**Comment by TragicCaesar** [comment]
Is that me？I don't know.

**Comment by TragicCaesar** [comment]
OK, so what should I do then

**Comment by thedillonb** [comment]
@TragicCaesar, is it you? I'm not sure what you should do...

**Comment by thedillonb** [comment]
@negebauer, I think i've resolved the issue. I'm not sure how, but it looks like one of your devices got registered twice - which would make sense. I've deleted the duplicate so you should stop seeing copies of everything ;)

**Comment by TragicCaesar** [comment]
There are so many msg suddenly appear in my codehub scaring me to death, I'm in a class and maybe I'll check them later

**Comment by thedillonb** [comment]
@TragicCaesar, if you'd like to limit the messages that come from this repository you may want to "Unwatch" it

**Comment by negebauer** [comment]
@thedillonb Perfect. I'll let you known how it goes, tomorrow at best. Again, thanks for the quick response!

**Comment by negebauer** [comment]
@thedillonb I haven't received a duplicated notification for all day
I guess it working
Closing the issue thanks
Thanks!

**Comment by sclukey** [comment]
@thedillonb I have this issue as well. I'd hate to think you need to manually fix this every time it happens, perhaps you could automate a check and fix for this? Or I guess figure out why it is happening to begin with. Anyway in the meantime could you fix this for me? :)

**Comment by thedillonb** [comment]
@sclukey, the the problem is unfortunately the db which requires a bit of work to swap out persistence stores - so I haven't finished that yet. In the mean time, you should be all set.
