### ISSUE TITLE
Cannot access private repositories

### ISSUE THREAD

**Issue by marckrejci** [thedillonb/CodeHub#170]
I've upgraded to your Pro edition and I'm not able to access any of my private repositories. Known bug or user error? Thanks!

**Comment by thedillonb** [comment]
Are you still getting the "Upgrade to Pro" popup when you visit your private repositories?

**Comment by marckrejci** [comment]
No. I'm not able to see any of my private repositories. They simply don't show up in the app anywhere. If I visit the "Pro Upgrade" section, the button says "Pro Already Enabled!" since I've paid already.

Thx for looking into it!

**Comment by thedillonb** [comment]
Wait, so you don't even see your private repositories in "Owned" repositories list? Regardless if you bought Pro or not, you should still see private repositories listed (along with your public repositories). The fact that you don't even see them in the list may be a deeper, fundamental issue. These repositories don't also belong to an organization do they?

**Comment by marckrejci** [comment]
Yes. I only really use it for private repositories in a few Organization accounts that I own. Here's a screenshot of the "Owned" tab in your app: https://imgur.com/a/43HYh

**Comment by thedillonb** [comment]
Ah ha! I believe you're hitting a common issue that many people do around Organization permissions for 3rd-party access. GitHub recently changed how Organizations, in particular, grant permissions to 3rd-party apps (like CodeHub). The fix is simple, if you go to GitHub.com in your computer browser, click your user profile picture on the top right, go to "Settings", then on the bottom left you should see your Organizations. Go to each one and choose the "Third-party access" section and make sure your policy is set to not restrict the app.

**Comment by marckrejci** [comment]
Boom! That did it. #solved

**Comment by thedillonb** [comment]
Outstanding! Good to hear it's working. Let me know if you have any other questions, or comments.

**Comment by pietrocaselani** [comment]
I have pro upgrade enabled but still can't see the organization private repos. And CodeHub isn't showing up on Third-party application access policy.

**Comment by arnoldse** [comment]
I have the same issue - upgraded to Pro. But I can't see the organization private repos, either... And CodeHub isn't showing up on 3rd part app access as well.

**Comment by thedillonb** [comment]
Do the organizations belong to you? There's an easy way to grant access if it's not showing up. Go to your settings page (https://github.com/settings/connections/applications), applications, then click on `CodeHub`. At the bottom you'll see your organizations with a button allowing you to grant access to it.

<img width="855" alt="screen shot 2016-11-30 at 8 37 20 pm" src="https://cloud.githubusercontent.com/assets/1644068/20778613/d3b35e7a-b73c-11e6-8808-b210e5e3e0cd.png">

**Comment by arnoldse** [comment]
Oh, thanks for this info! Now, it works for me!
