### ISSUE TITLE
"The request to load this item did not complete successfully!" error for opening a private repo

### ISSUE THREAD

**Issue by mrraedb** [thedillonb/CodeHub#172]
I keep getting this error whenever I try to open someone else's private repo that I'm a contributor to - the error also mentions "value cannot be null. parameter name: input".

**Comment by thedillonb** [comment]
Hmm. Let me peak around the source tonight and see if I can't find the answer to this.

**Comment by thedillonb** [comment]
I think I fixed this. I couldn't get it to reproduce exactly like you mentioned but I did get it to produce the same error by doing something similar. The fix will be in the next release. Thanks for pointing this out!
