### ISSUE TITLE
Filtering trending repos fails

### ISSUE THREAD

**Issue by RobertAudi** [thedillonb/CodeHub#174]
The last language (alphabetically) that does not throw the error in my experience is `J`. 

![Screenshot](http://i.imgur.com/i2sZ3sW.jpg)

**Comment by thedillonb** [comment]
@RobertAudi, give it a try again. I believe I resolved it, or at least can no longer reproduce this on my device. All it took was a tweak on the trending API.

**Comment by thedillonb** [comment]
Closing as this has been fixed - or at least I can no longer reproduce this.
