### ISSUE TITLE
Upgraded to Pro. CodeHub says, no good!

### ISSUE THREAD

**Issue by bipinu** [thedillonb/CodeHub#177]
So I just installed CodeHub, and then just upgraded to Pro. Because why not!
- Tried accessing private repos, CodeHub asks me to upgrade. 
- Since I have already upgraded, I close app, open it, and then use that tiny text link to "activate". 
- CodeHub says activated, I say thank you!
- Browse to Private repo list, see private repos, click on one of the private repos...aaand it's overlayed with an upgrade notice.
- Private repo belongs to an organization. Device iPhone 6. iOS v9.3.

I feel like Marvin, the depressed robot.

**Comment by thedillonb** [comment]
The answer is 42.

When the app says "Activated" does the "Purchase" button turn blue and say "Pro Enabled"? I can't quite figure out why the flag would not be getting set if you're seeing the "Activated" sign. Your device is not jailbroken is it? I've seen some strange phenomenon with jail broken phones. Regardless, I'm going to spend my day trying to reproduce this tomorrow. I'll try and throw some code together and spin another release ASAP. Sorry for the inconvenience.

**Comment by bipinu** [comment]
_Yes 42 is all hunky-dory, but what's the question?_

Nupes, it doesn't say that. (Screenshot attached!)
Device isn't jail-broken either.

![img_1241](https://cloud.githubusercontent.com/assets/78911/14182374/3bfd1e0e-f76b-11e5-934a-2bbacb95cbee.jpg)

**Comment by thedillonb** [comment]
So I was able to reproduce this once over several requests. I'm not exactly sure what happened that one time, but I closed out of the app (killed the app via the switcher). Then clicked "Purchase" again and it went through. I'll keep searching through. A new version just came out today - which fixes some other issues, but you might try using that and seeing if it works. It's a long shot, but just maybe...

**Comment by bipinu** [comment]
Upgraded! Doesn't fix it.

However, something funny happens in the "News" view (it opens after I launch the app). I can see issues from my private repositories. However, clicking on them results in the same upgrade screen.

**Comment by bipinu** [comment]
@thedillonb Any updates on this. 
I tried to take the "uninstall-reboot-install-activate" route. Still nothing.

**Comment by thedillonb** [comment]
@bipinu, I put a few "fixes" into master and pushed out a release for Apple approval. Since I'm not able to consistently reproduce this I'm not certain this will fix the issue you're seeing. However, it should, if nothing else, add more error logging (to the screen) if the app is having trouble actually communicating with StoreKit. I'll keep you updated as it progresses through approval.

**Comment by thedillonb** [comment]
@bipinu, 2.9.0 was released yesterday which added a few "fixes" as well as better detailed error descriptions for App Store purchases. If you'd like to give it another try and see if that resolves your issue, or, at least gives you a better detailed error messages on why it's unable to proceed.

**Comment by bipinu** [comment]
Thanks for all the work. 
So I installed it and went for activation. Sadly the loader never stops. 
If I relaunch the app, I get the following error message for a brief second or two: "Error Purchasing : object reference not set to an instance of an object "

![image](https://cloud.githubusercontent.com/assets/78911/14405773/d0c66118-fe95-11e5-935b-0e807ef4ec9f.png)
![image](https://cloud.githubusercontent.com/assets/78911/14405796/5610e82a-fe96-11e5-9c25-f7dd12a574f9.png)

**Comment by bipinu** [comment]
@thedilonb Any luck with error logs?

**Comment by thedillonb** [comment]
@bipinu, I've seen two errors get reported back around iTunes issues in the Chinese local. I don't suspect that is your issue, but it has brought to light that there's an internationalization issue going on with language local that may be causing some issue here. Someone else actually mentioned they were unable to restore purchases and actually provided a video. So, that will go along way to resolve this. Hopefully I will be able to get a handle on this tonight and spin a new version ASAP! I really appreciate your patience. I wish I could have resolved this faster but for some reason the answer has escaped me for some time :/

**Comment by nickjacques** [comment]
@thedillonb I'm glad the video helped! Let me know if there's anything else I can do to help out :)

**Comment by bipinu** [comment]
@thedillonb Thanks! I appreciate the efforts.
The latest update (v2.9.1) didn't fix the issue either, btw.

**Comment by thedillonb** [comment]
A new update is under review right now (2.9.2) which, I think 🙏 , finally fixes this issue.

**Comment by nickjacques** [comment]
@thedillonb That's great news! I'll definitely check it out as soon as it's available on the App Store. Thanks for digging into this problem!

**Comment by nickjacques** [comment]
Just updated to 2.9.2 and was able to restore my purchase with no problems. Thanks @thedillonb for the fix - much appreciated!

**Comment by bipinu** [comment]
Thanks @thedillonb. This release didn't fix my problem, but I think I have the error message that may finally help you resolve it:
"Error Purchasing
Unable to restore transaction as iTunes returned an empty product identifier"

**Comment by thedillonb** [comment]
@nickjacques glad that fixed your issue. Now for @bipinu, the fact that you're seeing that error message is extremely perplexing. The code path you're hitting is

```
var productId = transaction?.OriginalTransaction?.Payment?.ProductIdentifier;
if (productId == null)
    throw new Exception("Unable to restore transaction as iTunes returned an empty product identifier!");
```

which should never be hit. When you restore your transactions iTunes is **supposed** to return the original transaction and it's identifier. For it to come back empty makes absolutely no sense. It's like iTunes knows you purchased it, but has no actual record of what was purchased... No wonder this was so hard to reproduce.

**Comment by bipinu** [comment]
Hahaha Don't you love writing code?

**Comment by bipinu** [comment]
@thedillonb Can something be done about this by contacting Apple support? Would I have to do it, or should you?

**Comment by thedillonb** [comment]
Hey @bipinu, are you talking about in reference to the bug or a refund? I actually spoke to a Apple tech guy who was not quite sure why, on a restore, iTunes would return missing data. However, he did suggest an alternative that I plan on implementing in the next version - which I've already submitted to Apple for review.

If you're looking for a refund, I unfortunately can't help there. Developers cannot offer refunds - you'll have to go through Apple: http://reportaproblem.apple.com/.

**Comment by bipinu** [comment]
Not a refund! Just checking if there even a way for the issue to be resolved through code.
Will wait for the next release.

**Comment by bipinu** [comment]
Hallelujah! I can see my private repos now. 
Thanks, Lord Commander!

**Comment by rycorkery** [comment]
why am i on this

**Comment by thedillonb** [comment]
@bipinu That's awesome news! Thank goodness this has been resolved. Thanks for sticking with me. I really appreicate it.

@rycorkery if you're not interested in getting notifications for this repository you may want to un-watch it.

**Comment by TennisGazelle** [comment]
That sounds great but Mr Buchanan what I think rycorkery is trying to ask about is what happened that made him (and me as well) part of this chain. 

Not that we don't see the inability to unsubscribe, but rather what did we do to get ourselves following this thread to be sure not to accidentally do this in the future.

Again. That sounds like an awesome feature fix and I'm not at all ragging about it.
--Have fun,
Daniel L.
