### ISSUE TITLE
Question of notifications 

### ISSUE THREAD

**Issue by soyRazo** [thedillonb/CodeHub#178]
codehub download page 17 activation notifications, delete the app because change my username and I was not in codehub, and appeared to re-install, but I have no notifications tells me to pay again.

**Comment by thedillonb** [comment]
@soyRazo, which notifications are you talking about? Github notifications or Push notifications? Github Notifications are free. You shouldn't have to purchase anything. Are you referring to push notifications?

**Comment by soyRazo** [comment]
Yes push notifications.
I had already paid the 17 and now that I returned to install is not activated, calls me pay again.
![](http://i.imgur.com/hV3W8xt.jpg)

**Comment by thedillonb** [comment]
Have you tried the "Restore" button? It should restore your previous purchases. You can also try to "buy" it again. iTunes will tell you that "You've already purchased, would you like to download it for free" (or something like that) and that should fix it too (You won't be charged for it if you've already bought it.)

Regardless, it looks like you're on a old version of the app. Are you running iOS 8?

**Comment by soyRazo** [comment]
Yes i have ios 8, what's the problem?

**Comment by soyRazo** [comment]
and I could solve it, thanks.

**Comment by ontheway1215** [comment]
why i often receive yours email 。

发自我的 iPad
