### ISSUE TITLE
Active account still logging in.

### ISSUE THREAD

**Issue by ghost** [thedillonb/CodeHub#18]
Tapping the currently active account in 'Accounts' will still show the 'Logging in...' HUD.

I think this should not happen as it is already logged in.

**Comment by thedillonb** [comment]
This has been fixed in the upcoming release (3.0). You will no longer see the "Loging in..." if you're obviously already logged in.

![oa4lvmcn4i](https://cloud.githubusercontent.com/assets/1644068/6882476/6728d6e0-d55c-11e4-8d40-f2aab382b146.gif)
