### ISSUE TITLE
Organization not shown in left bar

### ISSUE THREAD

**Issue by ibash** [thedillonb/CodeHub#180]
I upgraded to pro and am part of an organization but it does not show in the left bar.

We have restricted third party access, and I have owner privileges, but codehub does not show up in the list of apps to approve.

Any ideas on how to fix this?

**Comment by ibash** [comment]
Note that I temporarily removed application restrictions and the organization showed up. I reenabled restrictions, killed/restarted the app and it went away.
I *should* be able to auth this.

**Comment by ibash** [comment]
GitHub ui confused me, carry on

**Comment by thedillonb** [comment]
Haha, yeah the organization permissions on GitHub are not so straight forward.
