### ISSUE TITLE
Crash when trying to open issues

### ISSUE THREAD

**Issue by rsimenok** [thedillonb/CodeHub#182]
App crashing when trying to open issues from side menu, or from repo page but only if there are issues.

App Version 2.9.0(2.9.0.3)
iOS 9.3.1
Tested on: iPad Mini 2, iPod Touch 6.

**Comment by thedillonb** [comment]
Hmm. I don't seem to be able to reproduce this issue. However, I do see errors being reported via iTunes so I know it's happening. Luckily, I think I've fixed it and have submitted another version to Apple to resolve the problem. Thanks for pointing this out.

**Comment by thedillonb** [comment]
@rsimenok, this should be resolved in the latest version that was released today (2.9.1). If you're still seeing this feel free to open up this issue again and I'll take another stab at it.
