### ISSUE TITLE
Profile Avatar does not sync with current GitHub picture 

### ISSUE THREAD

**Issue by faciendum** [thedillonb/CodeHub#184]
Hi,

It seems like that if you're changing your current profile picture / avatar on GitHub, CodeHub won't sync with your assigned account and is still using the initial picture. 

-----

I've tried:

#Remove assigned GitHub account in the CodeHub app and reconnect it. => old avatar. 

#Deinstalled CodeHub app and installed it again and assigned my GitHub account to it. => old avatar. 

#Waited for like 3-4 hours. Still the old one shown. 

-----

//This is my first issue report please correct me if i could have done anything better. Thanks.

**Comment by SaadVirtus** [comment]
Folks 
Could you please unsubscribe me from this thread. Thanks 

Saad Hameed

** I either dictated this to Siri or typed with thumbs. Expect typos :-)

**Comment by thedillonb** [comment]
@SaadVirtus, you have to unsubscribe yourself - we can't unsubscribe you. You're probably "Watching" the repository when you might not want to if you don't want to receive messages.

**Comment by thedillonb** [comment]
@faciendum, that's really weird. Even deleting the app didn't resolve it?! That's really strange. I wonder if the GitHub API doesn't make the reflective change for some time. This is not a case I've ever tested for so I'm not sure how GitHub or the app handles it. Technically, every time you launch the app, it should look for a new avatar, if there is one, and update everything appropriately.

**Comment by SaadVirtus** [comment]
Thx 
Will do 

Saad Hameed

** I either dictated this to Siri or typed with thumbs. Expect typos :-)

**Comment by faciendum** [comment]
@thedillonb

Indeed - it's really strange. I know it's not a big deal and I guess I wouldn't have noticed either if I didn't change my avatar yesterday. 

I'll keep you up to date if anything happens. 

Thanks for your reply. Greetings

**Comment by Walkersneps** [comment]
I experienced the same bug, but uninstalling the app and then logging again worked for me

**Comment by thedillonb** [comment]
I've got a fix for the next release. The app's cache is not flushed because the URL for the avatar doesn't actually change when you upload a new image - so it doesn't look like anything is different and prefers the cached version. Now, when you login the app, or switch users, it will destroy the avatar cache and allow the new one to be downloaded.

**Comment by faciendum** [comment]
Nice !

**Comment by faciendum** [comment]
Hey Dillon,

I've just installed the new version. 
Right now I'm not able to see my profile picture at all. It is just showing the default GitHub one. 

I tried the same things I did with the last version. Still no picture showing. 

Did you deployed this Bugfix within the current version ?

Greetings.

**Comment by thedillonb** [comment]
Hello @faciendum,
you just see a default image? The gray one with the GitHub cat inside? That's really odd. The bugfix for the avatar changes did go into the 2.9.2 release. However, for you not to get an avatar image **at all** is really perplexing. To double check I just deleted the app on my phone, installed it from iTunes, and logged in, this is what I see:

![image](https://cloud.githubusercontent.com/assets/1644068/14722551/0ea382de-07da-11e6-8d7a-50f37df88cb7.png)

My avatar populates in the top left, and where the "Events" menu item is. So, from what I understand, you just see the grey default image there?

**Comment by faciendum** [comment]
![](http://i.imgur.com/TUrb7fy.jpg)

Hey @thedillonb 

This it what it looks like for me. 
It is actually exactly like you said. I'm using he latest iOS on iPhone 6S and the latest released version of CodeHub. I have no GitHub subscription even though this wouldn't change anything I guess. 

Tried to reconnect my account twice and reinstalled the app after restarting the iPhone.

I'm sorry that I'm not able to give you more details due to the fact that I'm not even recovering an error message or something. Just strange.

**Comment by thedillonb** [comment]
@faciendum that's really odd. Are any avatars loading for you?

**Comment by faciendum** [comment]
@thedillonb good news - i've just changed my avatar in hope that i just had to trigger the event. I couldn't see my Avatar immediately but long story short:

im able to see not only mine, but also everyone else avatar right now 👍

**Comment by thedillonb** [comment]
@faciendum, that's fantastic to hear. I can't fathom what was occurring but I hope it never happens again. The app does use the underlying URL transport mechanism of iOS so perhaps it had a specific response cached for that image? I'm not really sure, but glad you've been able to resolve it.
