### ISSUE TITLE
[question] callback URL?

### ISSUE THREAD

**Issue by shenAlexy** [thedillonb/CodeHub#190]
Please help to me, How to set up the Authorization callback URL in Developer applications? I  want to sign in my App though Safari.

**Comment by thedillonb** [comment]
@shenAlexy, correct me if I'm wrong, but your question doesn't seem to have anything to do with CodeHub. If you're looking to implement the OAuth flow through GitHub I suggest you check out their documentation: https://developer.github.com/guides/basics-of-authentication/

**Comment by shenAlexy** [comment]
Okay.
