### ISSUE TITLE
Don't show organizations repositories on profile

### ISSUE THREAD

**Issue by negebauer** [thedillonb/CodeHub#193]
When I click on my profile and then on repositories it shows all my repositories and those that belong to the organizations of which I'm part

This shouldn't be like this
On my profile I should see only my repositories and if I want to see the repositories of one of my organizations I would go to said organization profile to see them

**Comment by thedillonb** [comment]
Will be fixed for the next release

**Comment by negebauer** [comment]
Nice! I'll be waiting for it 🙏
