### ISSUE TITLE
Getting two notifications m

### ISSUE THREAD

**Issue by Mortiferr** [thedillonb/CodeHub#194]
I'm getting two notifications for everything and they're the exact same thing. For example someone recently merged a pull request and I got two notifications and it's really annoying. Why is this occurring?

**Comment by thedillonb** [comment]
Do you have two GitHub accounts on the app that are watching the same things? I'll can fix this on the back-end if that's not the case.

**Comment by Mortiferr** [comment]
No, I just have this one which makes it kind of odd. I could delete the app and reinstall and see if that helps?

**Comment by thedillonb** [comment]
I just removed the duplicate entry in the back-end registration. No clue how that happened but it registered you twice on the exact same second. I'll look into that, but for now, you should be all set!

**Comment by Mortiferr** [comment]
Thanks! Next time I get a notification I'll check.

**Comment by thedillonb** [comment]
Reopen if you see a duplicate.

**Comment by Mortiferr** [comment]
Fixed thanks
