### ISSUE TITLE
Star/watch/fork from appropriate lists.

### ISSUE THREAD

**Issue by IAP-Reloaded** [thedillonb/CodeHub#197]
In the CodeHub app, there are lists for
- Watchers
- Starrers
- And Forks.

You should be able to do that from the list itself:

![](http://i.imgur.com/vc3NdNZ.jpg)

**Comment by thedillonb** [comment]
I'm not sure I see an advantage to putting a selector in a list to choose "Star/Watchers/Forks" compared to what the app currently does where the previous screen allows you to click on "Star/Watcher/Forks". GitHub.com follows the the latter approach as well. These lists are actually one of the rarely visited views on the app - not many people even look at them. If you can come up with a solid argument to adding a selector I'm willing to reconsider. However, I'm going to close this as I believe the current implementation is sufficient.
