### ISSUE TITLE
There is a typo on the Go Pro! page

### ISSUE THREAD

**Issue by josiahaltschuler** [thedillonb/CodeHub#198]
On the Go Pro! page shown in the screenshot below, the word "availble" is misspelled. It should be changed to "available."
![img_0307](https://cloud.githubusercontent.com/assets/2493800/16025058/c402e226-318a-11e6-9f49-a8c4392c6f08.PNG)

**Comment by thedillonb** [comment]
Haha! Great find! You work on something long enough and you completely miss the obvious things. Thanks for pointing this out. I'll fix it in the next release.

**Comment by josiahaltschuler** [comment]
No problem, glad to help!

**Comment by thedillonb** [comment]
Fixed. Will be available in the next release.
