### ISSUE TITLE
what about your github dev flow

### ISSUE THREAD

**Issue by liujie15838028035** [thedillonb/CodeHub#199]
i see some  message in readMe.md .

    Fork it!
    Create your feature branch: git checkout -b my-new-feature
    Commit your changes: git commit -am 'Add some feature'
    Push to the branch: git push origin my-new-feature
    Submit a pull request :D

i also see some braches ,
i want to learn how about git dev flow ? can you tell me about your dev flow?

**Comment by thedillonb** [comment]
@liujie15838028035, the description in the readme is exactly my dev flow for external contributions. You can find a more detailed explanation here: https://guides.github.com/introduction/flow/

**Comment by liujie15838028035** [comment]
@thedillonb  thanks!

**Comment by liujie15838028035** [comment]
@thedillonb  , i have another question to ask .
If there is a project name mainProject on github pager,   i as a user , fork this mainProejct in my github proejct(user1/mainProject),  there are some branches in this proejct,  mater, develop, test;
there are  also some tags in it, V1.0, V2.0,V3.0.   if there are some bugs find in V2.0, 
i want to fixed it .  how can i use git to handle it ?
fixed this bug in V2.0, how can i add this fixed in master branch ?
