### ISSUE TITLE
Push Notification: The certificate for this server is invalid

### ISSUE THREAD

**Issue by Myfreedom614** [thedillonb/CodeHub#202]
Settings->Push Notifications->Got exception: 

> The certificate for this server is invalid. You might be connecting to a server that is pretending to be "push.codehub-app.com" which could put your confidential information at risk.

**Screenshot:**
![270388200126119956](https://cloud.githubusercontent.com/assets/2476467/16190460/f31d5802-3711-11e6-8eb6-1f5ba56fb97f.jpg)

**Comment by thedillonb** [comment]
Well, that's embarrassing. I renewed the certificate. You should be good to go. Sorry for the inconvenience.

**Comment by ahenderson1986** [comment]
Cheers matey

Best
Tony
