### ISSUE TITLE
iOS App Error: Unknown Secure Transport error `ClosedGraceful'

### ISSUE THREAD

**Issue by ibarnes** [thedillonb/CodeHub#203]
When ever I try to commit changes I get a popup with this error message. 

Unknown Secure Transport error `ClosedGraceful'

I did some searching online and it seems like an issue with calling the API via SSL. Here is a link that I found.

https://forums.xamarin.com/discussion/68802/xamarin-ios-update-unknown-secure-transport-error-closedgraceful

**Comment by thedillonb** [comment]
@ibarnes, are you connected to a GitHub Enterprise instance? You're right that a Xamarin change has occurred that brought rise to this issue. However, the change is that TLS 1.0 is no longer supported - which might be what you're hitting. If you're using a GitHub Enterprise instance, check what version of TLS the instance is using.

**Comment by brencerddwr** [comment]
I am having the same problem and I am not on an enterprise account. I am using a free personal account on github.

**Comment by thedillonb** [comment]
Hmm, that's unfortunately. If @brencerddwr is getting this when he connects to GitHub.com then there is something wrong with that update. I'll look into this ASAP.

**Comment by stm-dev** [comment]
3 Weeks and still no update? :/

**Comment by thedillonb** [comment]
An update is coming. I am still waiting on a fix from Xamarin (https://bugzilla.xamarin.com/show_bug.cgi?id=41206). I am not excited about downgrading to TLS 1.0 to resolve this issue, as some have suggested, but will if there is no word from them with the week.

**Comment by thedillonb** [comment]
Just pushed an update to Apple to resolve this issue (2.9.5). Expect this to be public within a few days.

**Comment by ibarnes** [comment]
Sorry guys I had notifications off on the app and the email went to my spam folder. I'm no longer having this issue. Did you guys fix it?

**Comment by thedillonb** [comment]
Yeah it's been fixed.

**Comment by dipakdipak** [comment]
This issue still persists. I am using Xcode Version 12.5 (12E262). And this is the latest version. 
If there is any ways to fix this please let me know. Thanks everyone in advance.
