### ISSUE TITLE
why codehub ios pad client cannot support download source code?

### ISSUE THREAD

**Issue by puXiaoyi** [thedillonb/CodeHub#209]
i can download source code in iPhone using CodeHub client for offline reading. but in iPad, the CodeHub client is different, i cannot find download entry. i felt so disappointed, because iPad is bigger than iPhone , and more suitable  for people to read code than  iPhone. how can i read offline code in iPad.
i am a chinese, sorry for my poor english. thank you.

**Comment by thedillonb** [comment]
Hello @puXiaoyi, CodeHub is not a **Git** client so it does not provide offline viewing of source code. CodeHub is a **GitHub** client so offline code viewing is not a current feature as managing your GitHub account always requires internet access. If you're looking for a Git offline client then I suggest checking out http://git2go.com/. It's a great app that allows you to pull down your code and view it anywhere.

**Comment by tangguanglei** [comment]
@puXiaoyi  how can you download code in iPhone?

**Comment by littleglass** [comment]
i just copy  and paste.
 or  you  can open by WPS  and then share by qq.

  i don't  know other methods any more.
