### ISSUE TITLE
Huge swathes of comments on a long Issue don't load

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [thedillonb/CodeHub#221]
So, regularly, scrolling through the comments on an Issue, the comments will stop rendering halfway-ish through:

![rendering failure, half-empty page of comments on iOS](http://i.ell.io/14QVl+)

(Note the position of the scroll-bar on the right!)

I'm on the iOS 10 beta.

**Comment by ELLIOTTCABLE** [comment]
(Issue in the screenshot: Dropbox/hackpad#51.)

**Comment by thedillonb** [comment]
Whoa! Is that a public issue I could take a look at to reproduce?

**Comment by ELLIOTTCABLE** [comment]
@thedillonb this applies to basically every Issue I view; but I linked the specific one above.

(While we're at it: that link *also* isn't rendering in the app; does it not support GFM? … Should I submit this as a separate Issue? :P)

**Comment by docwhat** [comment]
Docker has lots of long issues that trigger this bug.

**Comment by RolfKoenders** [comment]
I encounter this on allot of issues. Not specifically long ones. Also on this particular issue.. 
iOS 10 GM
iPhone 6S Plus

**Comment by AlecRust** [comment]
Also getting this on most issues, iOS 10 iPhone 6S.

**Comment by bgrainger** [comment]
I'm seeing this with CodeHub 2.9.7 on iOS 10.0.2. Sample issue is bgrainger/MySqlConnector#67

![img_8604](https://cloud.githubusercontent.com/assets/188129/19048941/3af0d2ec-895d-11e6-8088-da0ba934cb6c.PNG)

**Comment by thedillonb** [comment]
Fix is inflight. I'll submit it to Apple tonight. Hopefully you'll have a fix mid week. Sorry for the delay.

**Comment by thedillonb** [comment]
This should be all set now in the latest version that was just released to iTunes. It happened to be an iOS 10 bug that other developers have also seen. I believe there is even a Radar filed against Apple for this issue. I've managed to work around it via a suggestion on StackOverflow. Hopefully this completely resolves the issue for all users.
