### ISSUE TITLE
Username not shown

### ISSUE THREAD

**Issue by tommy-muehle** [thedillonb/CodeHub#222]
Hi,

to begin, thanks for this amazing App. I use it every day.

Today i saw a small bug in the news section. I missed the name of a contributor which was added to a repository. See these screens for more details:

iOS App:
<img src="https://cloud.githubusercontent.com/assets/1351840/18629803/5cfd608a-7e68-11e6-93c8-b11014ae855b.PNG" width="250">

Github on Desktop:
<img width="500" alt="bildschirmfoto 2016-09-19 um 12 11 51" src="https://cloud.githubusercontent.com/assets/1351840/18629765/14536744-7e68-11e6-8e45-9a8423d9463b.png">

iOS App in Version 2.9.7

Best regards
Tommy

**Comment by thedillonb** [comment]
Ah great catch!
