### ISSUE TITLE
Photo

### ISSUE THREAD

**Issue by MarseilleDev** [thedillonb/CodeHub#224]
# Where is my profile photo? ![](http://i.imgur.com/XeW9jeF.jpg)

**Comment by thedillonb** [comment]
Closed via #233

**Comment by MarseilleDev** [comment]
# See, if I change the picture on different picture, it is displayed in the program.

![GitHub](https://cloud.githubusercontent.com/assets/19198757/19410802/8f6335a0-92fd-11e6-8081-7774295932b1.png)

![CodeHub](https://cloud.githubusercontent.com/assets/19198757/19410803/8f66f226-92fd-11e6-9b36-590018a2a6cc.png)
