### ISSUE TITLE
Endless Cycle

### ISSUE THREAD

**Issue by eshirima** [thedillonb/CodeHub#226]
[Video](https://goo.gl/DrbmCT) Proof

**Comment by thedillonb** [comment]
Is there something wrong with that? What would you expect to happen?

**Comment by eshirima** [comment]
Shouldn't there be a safeguard of some sorts? Meaning while looking at repo contributors, I should not be able to click on myself.

**Comment by eshirima** [comment]
Since we know for a fact that all repos will contain `currentUser`, then why not simply disable user interaction on the cell that has `currentUser`?

**Comment by thedillonb** [comment]
I see where you're coming from, but I'm unsure if there is any harm in allowing the user to navigate back to himself. Much like in the browser, GitHub doesn't prevent you from going into your own repositories, clicking on your own name, going to your repositories, clicking on your own name, etc... Even in the app, if I go to one of my repositories, should I be disabled from clicking on my own profile from within the repository view? If I was, and I wanted to get to my profile, I'd have to open the slideout menu and reset the navigation. Effectively ditching where I currently was in the view hierarchy.

**Comment by thedillonb** [comment]
Closing this as I believe the current functionality is operating correctly.
