### ISSUE TITLE
Organisations Not Updating

### ISSUE THREAD

**Issue by MaXwellFalstein** [thedillonb/CodeHub#231]
The organisation menu and organisation view are not updating the list of organisations.

I used to be in two organisations, now I am in four.

GitHub.com sees I am part of the four organisations, but CodeHub sees I am in two and will not let me edit anything on the two newer organisations.

**Comment by thedillonb** [comment]
Do you happen to know if "Third-Party Access" is enabled on those two other organizations? (https://help.github.com/articles/enabling-third-party-application-restrictions-for-your-organization/). This is almost always the case with CodeHub not seeing, or allowing you to edit, organization resources. When CodeHub asks GitHub for the organizations, if they're third-party disabled, it won't even return them as you being in them.

**Comment by MaXwellFalstein** [comment]
Third party access is enabled on the other two organisations.
I cannot get CodeHub to request access as I do not want to open up the two organisations to all third parties.
CodeHub should request access for third party access to be granted, but I cannot get it to work. Is this something you would need to add or is it part of the system already?

**Comment by thedillonb** [comment]
CodeHub cannot request third-party access for organizations it doesn't know about. GitHub implemented third-party restrictions to explicitly prevent unauthorized apps from accessing *anything* about specific resources. Unfortunately, there isn't anything the app can do. You, as a user, have to explicitly request access to the organization for an application.

**Comment by MaXwellFalstein** [comment]
Okay, where is the ability to explicitly request access to the organisation for the application?

From what I can see it just shows me what my personal applications are when on the organisation screen. It goes back to my settings not authorising the organisation applications.

**Comment by MaXwellFalstein** [comment]
I have worked out what is going on and everything is fixed.

All four organisations needed re authorising on https://github.com/settings/applications.
