### ISSUE TITLE
Not all repositories showing up and cannot search for them.

### ISSUE THREAD

**Issue by MaXFalstein** [thedillonb/CodeHub#234]
I have 140 odd repositories.

Only 100 of them are showing up.

I cannot search for any repository starting with a P or further down the list.

This is the same in my account and my organisations with more then 100 repositories.

**Comment by MaXFalstein** [comment]
This has become worse now that I have 198 repositories.

I cannot view more than 100 repositories on any user's account.

**Comment by Bruce12** [comment]
That's really bad!is that a bug of GitHub?

**Comment by thedillonb** [comment]
This has been resolved as of 2.10.1. Pagination has been fixed which will allow you to view past 100.
