### ISSUE TITLE
Duplicate push notifications

### ISSUE THREAD

**Issue by christopherthielen** [thedillonb/CodeHub#236]
this is a dupe report of #167 

I am getting three notifications, can you check my account in the database?

----

@thedillonb thanks a lot for maintaining code hub. I use it all the time!

**Comment by cstuder** [comment]
Hello, I'm affected too. A couple of weeks ago I started getting notifications three times in a row.

Today they started showing up four times in a row.

![november_13__2016_at_0239pm](https://cloud.githubusercontent.com/assets/288493/20246077/70f9d7e0-a9af-11e6-9c47-c29570cb95c5.png)

**Comment by christopherthielen** [comment]
I uninstalled, then re-installed CodeHub.  

I "restored purchases" and re-enabled notifications.  I'm back to one push notification per event.

cc: @cstuder

**Comment by thedillonb** [comment]
I've been rewriting the backend for push notifications as this is a a race condition in the sqlite database that's being used when requests come in quickly for the same user. I should have this all sorted out by the end of the week. Sorry for the inconvenience.

**Comment by thedillonb** [comment]
@christopherthielen @cstuder, are you guys still seeing duplicate notifications? I purged the database of duplicate entries so you should have been seeing only one notification for a few days now.

**Comment by christopherthielen** [comment]
@thedillonb I'm only getting 1 notification now.


--


FYI, every once in a while, codehub forgets my credentials and presents me with the "new account" screen.  Each time I re-entered my github credentials it asked if I wanted to receive notifications, and of course I kept saying "yep!"  I assume this is the reason I was getting the duplicate registrations.

**Comment by thedillonb** [comment]
@christopherthielen there was a bug in the previous version where the credentials were accidentally getting wiped that is resolved in the latest version in the app store. Are you on that version, and if you are, are you still seeing that?

As for your second point, that's most likely a bug. Saying "No" is currently just telling iOS not to produce a push notification token for the backend. However, if you had previously said yes, then the backend push services doesn't get updated of your new choice - that's a miss on my part. I'll create a follow up issue for that.

Good to hear you're only getting one notification now though 😄
