### ISSUE TITLE
Bug with of organizations.

### ISSUE THREAD

**Issue by MarseilleDev** [thedillonb/CodeHub#239]
# Where is this my organization?
![Profile](http://i.imgur.com/NJLINU4.jpg)
![Events](http://i.imgur.com/BPX25xW.jpg)

**Comment by thedillonb** [comment]
Is your organization restricting third-party access? That would by why its not showing up in the app.

**Comment by susu79** [comment]
sorry ，I'm Chinese ，so I don't understand。


发自网易邮箱 iPhone 版
在2016年12月01日 09:31，Dillon Buchanan 写道:

Is your organization restricting third-party access? That would by why its not showing up in the app.

**Comment by llity** [comment]
@susu79 为你的组织是不是不允许三方应用获取访问权限...

**Comment by wolfgangbaums** [comment]
please delete me from this stuff

**Comment by susu79** [comment]
ok！please wait 


sorry


发自网易邮箱 iPhone 版
在2016年12月01日 14:26，wolfgangbaums 写道:
please delete me from this stuff

**Comment by thedillonb** [comment]
@wolfgangbaums simply un-watch the repository if you no longer want to receive notifications. We can't do that for you.

**Comment by thedillonb** [comment]
Closing this as organization access unavailable to CodeHub if the user does not grant explicit access to it - it's completely invisible to CodeHub.
