### ISSUE TITLE
Auto Subscribe user!!

### ISSUE THREAD

**Issue by madeny** [thedillonb/CodeHub#245]
Hi, 
Every time I use the app on my iPhone I start to get notification I tried to disable it a few time but I'm still subscribed. plus fix that.

**Comment by LuuuuuG** [comment]
Excuse me?
On 12/26/2016 16:30, Madeny Diawara wrote:

Hi,
Every time I use the app on my iPhone I start to get notification I tried to disable it a few time but I'm still subscribed. plus fix that.

**Comment by madeny** [comment]
I did already! but still getting notification I never subscribe or start  any issue related  CodeHub before.

so I know what I'm talking about. so I can continue muting or disabling the thread that I'm not interested in.

I've been dealing with it a few months  but now I'm tired so please investigate in instead of giving some GPs.

**Comment by thedillonb** [comment]
Deleting comment from LuuuuuG since it adds no value.

@madeny, users are not auto subscribed to notifications. If you're referring to iOS push notifications then you can simply disable them in Settings if you'd like. If you're referring to GitHub notifications (emails) from the CodeHub repository then you can simply "Unwatch" the repository.

**Comment by ThatSpaceGuy** [comment]
Hello @thedillonb, I believe @madeny is referring to the fact that once a
user logs in to the CodeHub app for the first time, they are suddenly
e-mail subscribed to every GitHub issue for the CodeHub repo (maybe only
new issues?).  I myself was dismayed to find that I started receiving
e-mail updates (not app notifications) for multiple GitHub threads without
any opt-in.  I deleted the CodeHub app after realizing that it did not show
my commit history grid, but I am still subscribed to all the e-mail
threads.  I now need to take the time and unsubscribe on the GitHub site.

Please make it clear to new users that they will begin to receive e-mail
updates once they link their GitHub account.

Thank you for listening,
Luis

---
Luis H. Matos <https://www.linkedin.com/profile/view?id=24584972>
ReachLuis@Gmail.com
612-396-4995

**Comment by ThatSpaceGuy** [comment]
Sorry, I missed your instructions to Unwatch the repo.  I have done that
now.  Thank you.

**Comment by thedillonb** [comment]
@ThatSpaceGuy the app doesn't sign you up for anything automatically. When you first started the app, it it prompted you with it's little welcome screen. Did you happen to hit the "Watch" button on the "CodeHub is Open Source bla bla bla" page? If you did, then it does add you as a watcher of the repository. Just like if you hit the "Star" button it would have starred the repository for you.
