### ISSUE TITLE
Add email subject when an item is shared to the Mail app (or similar)

### ISSUE THREAD

**Issue by DavidHaslam** [thedillonb/CodeHub#253]
It would be a useful enhancement to add the email subject by copying (e.g.) the name of a repository or the title of an issue, etc

**Comment by DavidHaslam** [comment]
If anything further along this line could be implemented, such as also including the description of a repository in the message body, on a separate line to the link, that would be even better

**Comment by CodingMeUp** [comment]
Are you referring to the application of codeHub?

**Comment by DavidHaslam** [comment]
Why else would I have added this suggested enhancement?

If you're using CodeHub to explore repositories, and you come across one that's of interest, it's a sensible thing to email yourself as a reminder to look into it further, or to email a friend that might be interested.

It's inefficient to have to type in the email Subject.

Could there be a way to automatically copy something into the Subject field of the email?

Does the iOS share API even allow for such a possibility?

David

**Comment by thedillonb** [comment]
@DavidHaslam, I can definitely add the name of the repository to the subject. Do you think I should do "<username>/<repository>" or just the repository name? In addition to the URL, is there anything else you think I should add to the body of the email? Repository description?

**Comment by DavidHaslam** [comment]
Anything would better than a blank subject field.

Including the repo description as well as the URL in the email body is a great idea.

David
