### ISSUE TITLE
Add Wiki option 

### ISSUE THREAD

**Issue by DavidHaslam** [thedillonb/CodeHub#256]
Might it be useful to provide an option to access the Wiki for a GitHub repository?

**Comment by jon1746** [comment]
unsubscribe

**Comment by thedillonb** [comment]
@jon1746, you must unwatch the repository if you're not interested in receiving notifications. I'm deleting your comment for brevity on this thread.

**Comment by thedillonb** [comment]
@DavidHaslam, unfortunately there is no Wiki API available. I found it really odd too when creating the app, but there's no way to change the Wiki via any API that i've found.

**Comment by DavidHaslam** [comment]
Thanks for the details.
