### ISSUE TITLE
Login error: You are unauthorized to view the requested resource

### ISSUE THREAD

**Issue by coraxx** [thedillonb/CodeHub#266]
Hi, I need some help :) I wasn't using CodeHub on my iPhone 5 for a while and opened it up yesterday and I was greeted by the "New Account" screen. Okay, reentered my credentials and saw that CodeHub now needs more access, awesome, yes accept... then the "Logging in" wheel appeared and this error was thrown: "Error! You are unauthorized to view the requested resource"

I make the rest short. Removed CodeHub from iPhone, restarted iPhone, revoked CodeHub access on GitHub, reinstalled CodeHub and went through the short app introduction. Logged in, granted access for CodeHub and then again, the error was thrown.

Does somebody know what's going on? I somehow have the feeling, the problem may be on GitHub's API side, but really I have no clue.

I'ld appreciate your help a lot. Thanks in advance.

Cheers,
J

Sidenote: I also restored my "CodeHub Pro Version", same error happens when I again try to login.

Some screenshots:
![1_codehub_issue](https://cloud.githubusercontent.com/assets/19515548/23058868/4471ac82-f4f7-11e6-8d0e-e0e6f12bab04.jpg)
![2_codehub_issue](https://cloud.githubusercontent.com/assets/19515548/23059178/7f00f69a-f4f8-11e6-8e2d-502f28b562a4.jpg)
![3_codehub_issue](https://cloud.githubusercontent.com/assets/19515548/23059177/7ee18ce2-f4f8-11e6-884e-863c5612f7b9.jpg)

**Comment by punchsportdrink** [comment]
Just purchased this app and am having the same problem.

**Comment by danrademacher** [comment]
I'm having same issue. Had been using fine in past but was having syncing issues with some new repos. Thought I'd revoke access, reinstall to see if that fixed things. Instead I can't login at all. 

Re whether this is a Github API issue - i did try a couple other github iOS clients and trident is also throwing errors. GitBucket logged in successfully but is read only AFAIK. Maybe some new issue with apps that ask for write access?

**Comment by coraxx** [comment]
I just had issues with [SourcTree ](https://www.sourcetreeapp.com/) as well, regarding the same authorization step... very weird. Seems some fishy callback business is happening :(

**Comment by Colobri** [comment]
This also happened to me, downloaded it for the first time about 20h ago and still can't log in. No idea why. :<

**Comment by PhilippeCarphin** [comment]
I had this issue when I first got the app about a week ago.  I was trying to log in with my username and it gave me this exact error.  When I tried with my e-mail instead address it worked.

I did change my username so it may have worked with my previous username.

I logged out to test the theory.  And now I can't log back in with either my username or my e-mail.

**Comment by daumiller** [comment]
Just installed today. Tried logging in with both username and e-mail address. I get this error with both methods.

**Comment by thedillonb** [comment]
Hey guys, sorry for the delay in my response. I've figured out the issue and am in the process of pushing a new version of the app to the iOS store. I will ask them to expedite it as the app is pretty much non-functional as it is.

The sudden cause of this is that GitHub has added a empty `state` query parameter to the OAuth flow which is getting parsed incorrectly on the app side. I'm not sure what caused them to add this  query parameter all of a sudden or if it's actually a bug on their side.

**Comment by 4low** [comment]
Came here with the same issue after buying the pro version to try and fix it (I figured maybe it was because my only repo is private). 

Good to see it's already been fixed... 

I await the update!

**Comment by coraxx** [comment]
@thedillonb thank you for the quick response/fix. Now we only have to wait for apples app review mills ^^

Let's close this issue when the update was pushed, so people will find it in the issues section at first glance for now.

Cheers and thanks again!

**Comment by thedillonb** [comment]
@coraxx, good idea. I got a letter from Apple agreeing to do an expedited review but the app is still in "Waiting" status :man_facepalming:

**Comment by bgrrtt** [comment]
Thanks!

**Comment by sw95** [comment]
@thedillonb in my opinion the app listing should be suspended while it is not working ... I upgraded to pro before I found out it wasn't working...

**Comment by bywangxp** [comment]
i meet this question too

**Comment by thedillonb** [comment]
Removing an app from the app store takes 24 hours and then 24 hours to restore. On top of that, the latest version can still be redownloaded by previous users. The time at which this issue was discovered, fixed, submitted to Apple, and when I received the confirmation of an expedited review was all within that time frame. My original feeling was that I had a better chance of getting this through an expedited review (which usually is a few hours after receiving confirmation) rather than waiting for it to be pulled, then restoring it - should I have known that it would be way longer I might have reconsidered that. The other thing to keep in mind is that the app is only broken for users loging in with GitHub.com accounts. It is not broken for Enterprise users.

**Comment by thedillonb** [comment]
The new version has been released that resolves this issue. You should be getting the update any time now. The app has also been restored to the app store so it may take 24 hours to come back for new users - I took @sw95's advice and removed it.

**Comment by coraxx** [comment]
Works like a charm! :)

**Comment by bgrrtt** [comment]
THANKS!
