### ISSUE TITLE
How to show organization private repository in CodeHub?

### ISSUE THREAD

**Issue by SailCPU** [thedillonb/CodeHub#267]
I belong to an organization named cobotsystems, and this organization has a private repository(cobotsystems/cobot_polishing). How can I see this repository in my CodeHub App? I've already upgrade to pro edition.
![screenshot from 2017-02-22 21 45 48](https://cloud.githubusercontent.com/assets/17603873/23214065/60fd0e28-f948-11e6-9f87-2479398505f0.png)

And, I also try to login as Enterprise account, and also failed.
![151840681](https://cloud.githubusercontent.com/assets/17603873/23214720/b3e37594-f94a-11e6-8f54-b9f311f09778.jpg)
![1584249204](https://cloud.githubusercontent.com/assets/17603873/23214728/b8e85082-f94a-11e6-94a9-4c8204fe9c80.jpg)

**Comment by HomoDeus** [comment]
I met the same issue!

**Comment by thedillonb** [comment]
If your Organization is on GitHub.com then you don't need to login to a GitHub enterprise server (bottom 2 photos). The most likely cause of this is that your organization has 3rd party access denied. Take a look at: https://github.com/thedillonb/CodeHub#troubleshooting

**Comment by cIark** [comment]
中国移动亮了
