### ISSUE TITLE
what git merge tool do you used?

### ISSUE THREAD

**Issue by liujie15838028035** [thedillonb/CodeHub#277]
i use git , allwalys use git command,  sometimes , codes conflict, 
 what git merge tool do you used?
can you tell me ?

**Comment by liujie15838028035** [comment]
@thedillonb i use git , allwalys use git command, sometimes , codes conflict,
what git merge tool do you used?
can you tell me ?

**Comment by thedillonb** [comment]
@liujie15838028035 I use [Meld](http://meldmerge.org/). I encourage your enthusiasm but please refrain from opening issues within CodeHub that have nothing to do with the project. These types of questions are best suited for email or some other correspondence.

**Comment by liujie15838028035** [comment]
@thedillonb okay ! Thanks ! I always use github , write issue , pull request ,merge code by git command because of that I want the git log is a line!
