### ISSUE TITLE
I have a git problem , could you help me ?

### ISSUE THREAD

**Issue by 975545486** [thedillonb/CodeHub#282]
Hi,

I have a git problem , could you help me ?

when i use github , use git shell,  sometimes , i want to find some codes in history , what should i do ?

use git log ?  git blame ? git grep ?

could you help me ?
thanks !

@thedillonb

**Comment by xiaohuihui905423552** [comment]
sorry ,i don't konw

2017-05-04 16:48 GMT+08:00 975545486 <notifications@github.com>:

**Comment by Micle5858** [comment]
hello what is your name？where are you？
2017年5月4日(木) 17:51 Yanghui Li <notifications@github.com>:

**Comment by 975545486** [comment]
@Micle5858    I'm liujie , I'm in china !

**Comment by Micle5858** [comment]
加我微信号吧……micle5858
2017年5月4日(木) 18:11 975545486 <notifications@github.com>:

**Comment by thedillonb** [comment]
Guys, please do not use the issues here for non CodeHub related questions/issues.
