### ISSUE TITLE
Not Receiving any push notifications 

### ISSUE THREAD

**Issue by wangkesen** [thedillonb/CodeHub#283]
Hey there, just wondering if this is a big or maybe its because I'm on the latest beta build of iOS, but I don't receive any push notifications for the pro version even with it enabled.

**Comment by thedillonb** [comment]
@wangkesen I can't seem to reproduce this. I'm still receiving notifications but I'm on iOS 10.2.1. You can try going into CodeHub -> Settings -> And Toggling the "Push Notifications" button to see if that works. I'll try updating one of my devices to the beta and see if that reproduces the issue and get back to you.

**Comment by wangkesen** [comment]
@thedillonb Sounds good! I have the notifications set to on but it's still not working right now, tho this might just be a problem with the beta and it's almost time for another update so the issue might resolve itself with that. I'll keep you posted ![](http://i.imgur.com/0yrK1ur.jpg)

**Comment by PMacDiggity** [comment]
I am also not receiving push notifications, I've double check that notifications are allowed in system preferences and enabled in the app. I am running iOS 10.3.1

**Comment by SimonBlaurock** [comment]
I had the same problem but the fix is very easy. You must go in your account and then go to personal settings then to Notifications and then enable Web. 

Then you must Watch the Repository where you like to follow. 

If you then don't receive Notifications you must go in the personal settings to Authorized Applications and enable your CodeHub App.
After that the owner of the Organisation get a Mail. After he accept your App you are able to receive Notifications over your App. 
Sorry for my bad English.
I hope it is helpfully.

**Comment by PMacDiggity** [comment]
How do you add this to you authorized applications? This doesn't show up in my personal account settings, and I don't see anything in the app to add it.

**Comment by SimonBlaurock** [comment]
Not in the App. You must do this in your GitHub Account

**Comment by PMacDiggity** [comment]
I understand that, but I don't see CodeHub showing up in my list of authorized apps, how do I make that association?

**Comment by SimonBlaurock** [comment]
Hmm you must logging in with the same account. On GitHub and in the App.
The App automatically register in GitHub.

**Comment by PMacDiggity** [comment]
I am, the app shows my avatar, I can see the repos that my organization give me access to, and I've been able to flag those for watching, but I'm not getting the notifications.

**Comment by SimonBlaurock** [comment]
Then you must watch the Repositories that you like to follow.

**Comment by SimonBlaurock** [comment]
Go in GitHub to the Repository and click watching.

**Comment by paulmacdougall** [comment]
I've done that was well. I also switched accounts, and I can see the the CodeHub application now, but I still don't get the notifications, though I do get the watched repos emails. I should also note that this problem is also on my iPad and my iPhone.

**Comment by SimonBlaurock** [comment]
Do you really enabled the web Notifications in your account settings on GitHub?
It is next to the Mail Notifications

**Comment by wangkesen** [comment]
@SimonBlaurock @paulmacdougall I didn't actually have Web notifications enabled, only email under settings, and then notifications. Attached a pic just to show where it is in your settings for Github.

![notifications](https://cloud.githubusercontent.com/assets/25444572/26288754/0e4ba900-3ecb-11e7-8bfa-545027ca5665.jpeg)

**Comment by wangkesen** [comment]
That actually fixed it for me. Have to make sure its switched on in Github.com and as well in iOS under push notifications. Thanks for the patience closing issue now!
