### ISSUE TITLE
Error popup about no permissions or access

### ISSUE THREAD

**Issue by kellyalb** [thedillonb/CodeHub#284]
Immediately following upgrade to Version 2.10.1

**Comment by thedillonb** [comment]
Do you happen to have a screenshot? No permissions were changed in the release so that's very odd.

**Comment by kellyalb** [comment]
![img_0388](https://cloud.githubusercontent.com/assets/884889/26139427/999bfc8e-3a9e-11e7-90d0-27663c2043ce.PNG)

**Comment by kellyalb** [comment]
I just tried again and after a different error it loaded. ¯\_(ツ)_/¯ Thanks!

**Comment by kellyalb** [comment]
App crashed and it's having the same problem again.

**Comment by thedillonb** [comment]
@kellyalb I just pushed out another release a day or two ago with a change in the Login code that I **think** you might be hitting. If you get a sec, try it out and see if that resolves the issue for you.

**Comment by kellyalb** [comment]
Yes everything seems back to normal now. Thanks!!
