### ISSUE TITLE
Can not view source after selecting branch

### ISSUE THREAD

**Issue by ashtonmeuser** [thedillonb/CodeHub#286]
Using iOS 10.3.2 and CodeHub 2.10.1.

After clicking source on any repo and selecting a branch, I can not see the source code for any files nor can I navigate further into any directories.

**Comment by thedillonb** [comment]
I fixed this bug this morning and submitted it to Apple. We should see a fix within a day.

**Comment by ashtonmeuser** [comment]
Thanks for the quick reply 👍🏻

**Comment by thedillonb** [comment]
New release just got approved and released. You should see it on the app store soon.
