### ISSUE TITLE
Feedback should go to source code

### ISSUE THREAD

**Issue by CameronSamuels** [thedillonb/CodeHub#293]
The “feedback & support” should go to the codehub repo issues instead of uservoice, just like in codebucket. I like this better because you don’t have to login and most people like it more too. I think you will get more feedback doing so.

**Comment by thedillonb** [comment]
Great idea. I never liked UserVoice to be honest. It makes sense to send them here. However, I'm not sure what to do with Enterprise users who have their own GitHub instance.

**Comment by thedillonb** [comment]
This has been fixed in the latest version 2.12 (released today). The feedback will now send you to a place where you can create a feature/bug request or look through open items (github issues). This should tie in the feedback better with the GitHub project. Thanks for the suggestion!
