### ISSUE TITLE
Trending tab looks broken

### ISSUE THREAD

**Issue by garrettw** [thedillonb/CodeHub#294]
This is what I get when I go to the Trending tab. Same result no matter what language I select. Can't tap on any of the other options (daily/weekly/monthly).

![](http://i.imgur.com/e0SrtHu.jpg)

**Comment by thedillonb** [comment]
Yeah I'm in the process of fixing it. GitHub changed their HTML up so the backend isn't scraping correctly :/

**Comment by kittykat2111** [comment]
I'm . Still / trying to figure this out"

**Comment by thedillonb** [comment]
This should be fixed now. Thanks for reporting it.
