### ISSUE TITLE
Auto view master source if only branch is master

### ISSUE THREAD

**Issue by CameronSamuels** [thedillonb/CodeHub#295]
When you click on source to view the source of the repo, you have to click on a branch first. Make it where it doesn’t show the branches when there is one so it just automatically shows the master branch or the only branch.

**Comment by XiongJiangong** [comment]
don't send email to me any more




发自网易邮箱大师
On 08/05/2017 09:26, Dillon Buchanan wrote:

Closed #295 via 009b11e.

**Comment by liuhongli2120** [comment]
go away，do not send message to me


发自网易邮箱大师
在2017年08月05日 11:39，XiongJiangong 写道：
don't send email to me any more




发自网易邮箱大师
On 08/05/2017 09:26, Dillon Buchanan wrote:

Closed #295 via 009b11e.
