### ISSUE TITLE
Not Receiving Push Notifications

### ISSUE THREAD

**Issue by bobheadxi** [thedillonb/CodeHub#299]
I’m not currently receiving any notifications from the app.

On Github:
- Web notifications under `Settings > Notifications` enabled
- "Read Notifications" enabled under `Settings > Authorized OAuth Apps > CodeHub` enabled
- Following relevant repos and am receiving notifications on GitHub website

In App:
- Push Notifications under `Settings` enabled

In iOS:
- Notifications enabled under `Settings > CodeHub > Notifications`

Is there anything I'm missing?

**Comment by thedillonb** [comment]
You're not missing anything. Somehow the notification application became locked up and was unable to send outgoing iOS notifications. I've cycled the system and it looks to be running appropriately again. You should start seeing notifications rolling again. It looks as if I need a better alerting system - thanks for pointing this out.

**Comment by XiongJiangong** [comment]
don't send email to me any more




发自网易邮箱大师
On 07/29/2017 05:16, Dillon Buchanan wrote:

You're not missing anything. Somehow the notification application became locked up and was unable to send outgoing iOS notifications. I've cycled the system and it looks to be running appropriately again. You should start seeing notifications rolling again. It looks as if I need a better alerting system - thanks for pointing this out.

**Comment by bobheadxi** [comment]
Emails are automated, you can either un-watch the repo or disable email notifications in your GitHub settings

**Comment by alf3** [comment]
Please remove me from this endless stream of email.

Random numbers are too important to be left to chance.
