### ISSUE TITLE
notifications dont show up

### ISSUE THREAD

**Issue by webmavens** [thedillonb/CodeHub#303]
I am owner to many private git repo's, I want to be notified anytime there is a commit on those repo's, but I am not getting those notifications on the app.

Is there a setting I should be doing on github.com side on the repos? or they should just already work?

**Comment by pixelport** [comment]
+1 I bought Premium because I thought this feature would be included

**Comment by grammermao** [comment]
I donot understand what you say





发自网易邮箱大师
On 08/10/2017 20:30, pixelport wrote:

+1 I bought Premium because I thought this feature would be included

**Comment by pixelport** [comment]
I have a private github repo and subscribed to the notifications of this repo. When someone other makes a commit, no push notification is send. I thought this feature is included in premium.

Thanks

**Comment by webmavens** [comment]
Thanks @pixelport for rewording it... I am still facing this problem.  I was expecting to receive bulk of notifications every time there was a commit from my team on the repo's.  But I am not getting any notifications :-(

**Comment by thedillonb** [comment]
Looks like the VPS was having difficulties reaching out to GitHub. Should be fixed now.

**Comment by pixelport** [comment]
Thanks

**Comment by webmavens** [comment]
I am still not getting notifications :(
