### ISSUE TITLE
Contributing without an Apple Developer Account

### ISSUE THREAD

**Issue by bobheadxi** [thedillonb/CodeHub#308]
Not really an issue, but looks like without a paid developer account I can't create a provisioning profile to run the app in Xamarin Studio - am I stuck in that regard?

Unfortunate, was hoping to give contributing a try 😞

**Comment by grammermao** [comment]
Can you speak Chinese?




发自网易邮箱大师
On 08/10/2017 15:11, Robert Lin wrote:

Not really an issue, but looks like without a paid developer account I can't create a provisioning profile to run the app in Xamarin Studio - am I stuck in that regard?

Unfortunate, was hoping to give contributing a try 😞

**Comment by garrettw** [comment]
@grammermao Please unwatch this repository if you do not want to receive emails.

**Comment by grammermao** [comment]
Poor in English   Sorry😟




发自网易邮箱大师
On 08/10/2017 23:16, Garrett W. wrote:

@grammermao Please unwatch this repository if you do not want to receive emails.

**Comment by thedillonb** [comment]
@bobheadxi Unfortunately, without the provisioning profile there's no way to load it onto a phone. You maybe able to run it in the simulator on your Mac but besides that, I don't know of any other way to run the app.
