### ISSUE TITLE
Can't commit any changes

### ISSUE THREAD

**Issue by jskn** [thedillonb/CodeHub#309]
Just installed this app but can't save any commit. After editing a file and clicking on "save" nothing happens. 

Tried different repos. Using the Pro version on iPhone7 with the latest iOS.

**Comment by jskn** [comment]
To clarify. Saving changes to a file works but in the next step with view/screen "Commit message" nothing happens when clicking save.

**Comment by thedillonb** [comment]
Pushing out a fix for this right now.
