### ISSUE TITLE
Rename Explore tab to Search

### ISSUE THREAD

**Issue by garrettw** [thedillonb/CodeHub#321]
Would this be possible, along with an icon change to a magnifying glass? Cuz it is basically a search page, and I normally look for the word "Search" for this type of functionality. It took me a while to figure out where search was the first time I wanted to use it, and it still feels a bit weird to tap Explore for that.

**Comment by thedillonb** [comment]
Good call.

<img width="309" alt="screen shot 2017-08-27 at 12 56 25 pm" src="https://user-images.githubusercontent.com/1644068/29752173-3bbdf908-8b27-11e7-9c81-e658f681fea5.png">

Thats how it will now look in the next release.

**Comment by garrettw** [comment]
You added the ability to search for users too -- thank you!
