### ISSUE TITLE
After Unfollowing a user, remove related news items

### ISSUE THREAD

**Issue by DavidHaslam** [thedillonb/CodeHub#322]
News items include all events related to the users being followed. 

After you unfollow a user, it would make sense for the related items to be removed from News, even for past events.

**Comment by AmieOliveira** [comment]
It should be given as an option, though. "Do you wish to erase all data?" Or something to that effect.

**Comment by garrettw** [comment]
I could be wrong about this, but I think I've even seen this behavior on the web version – which tells me that this is probably not something CodeHub is doing, but rather a limitation of GitHub itself.

**Comment by thedillonb** [comment]
@garrettw is correct. This is completely governed by GitHub and it's API. Despite unfollowing someone, their API will still return past events with that user. While I'm not opposed to diverging from experience in the web this request would require a greater amount of work (network and cpu wise) just to accomplish this. The app would have to pull down all the users you follow (could be multiple API calls), then pull down the news, cross reference that and then display. Unless there is a huge outrage over having the users exist in the feed I don't believe this request is a common use-case (complaint).
