### ISSUE TITLE
iOS Beta Team testflight/hockeyapp

### ISSUE THREAD

**Issue by Shawzborne** [thedillonb/CodeHub#34]
Hi,

Can I be part of the iOS beta team to help find bugs and provide suggestions before public releases?

I have a testflight and hockeyapp account at theshawzborne AT gmail.com can you invite me to the beta build?

Thank-you,

Shawn

**Comment by moshed** [comment]
i would love to be part of the beta as well moshedancykier at gmail.com

**Comment by arturomc** [comment]
I would like to be part of the beta too, 4rturomc AT gmail DOT com, a big fan of your app already

**Comment by smileytechguy** [comment]
smileytechguy@smileytechguy .com pls
