### ISSUE TITLE
Add "Are you sure" toggle in settings (on by default) to prevent loss of data

### ISSUE THREAD

**Issue by Shawzborne** [thedillonb/CodeHub#40]
http://i.imgur.com/01G8C2G.jpg

When you press the back arrow while composing a new issue that has any data in it. Create a toggle in settings that gives you an option to turn on or off a pop up that asks are you sure you want to go back.

Because I was typing a decent size bug report and hit the back arrow key by accident and it just deleted the entire issue that I was just in the middle of composing. It would be quite upsetting if you had a nicely laid out, fairly large issue composed and you lost it all by accidentally hitting the arrow key which I did myself.

This would be a time saving addition to CodeHub for iOS

**Comment by thedillonb** [comment]
Version 3.0 will contain this feature:

![look](https://cloud.githubusercontent.com/assets/1644068/7217232/77b5aa44-e5ea-11e4-8b77-0196ff3ea05b.gif)
