### ISSUE TITLE
Icons not appearing in 2.2.1

### ISSUE THREAD

**Issue by Shawzborne** [thedillonb/CodeHub#47]
Icons not appearing in 2.2.1

http://i.imgur.com/lYTBT52.jpg

**Comment by thedillonb** [comment]
Fixed in the latest. Images now always reference their owner's avatar - downloaded and cached locally if non-existant.

![ios simulator screen shot feb 7 2015 3 09 13 pm](https://cloud.githubusercontent.com/assets/1644068/6093761/4b0c1af0-aedb-11e4-8bd9-fcc050198057.png)

**Comment by Shawzborne** [comment]
Looks great
