### ISSUE TITLE
Mine section completely incorrect 

### ISSUE THREAD

**Issue by Shawzborne** [thedillonb/CodeHub#54]
Mine section completely incorrect 

I have reported about 50 iOS tapatalk issues

Not 2..

http://i.imgur.com/MDC9HuR.jpg

**Comment by thedillonb** [comment]
Due to space restrictions, "Mine" will continue to be used instead of "Assigned To Me". If there was more room in the tab control then it would make sense to change it. But the restriction makes that hard.
