### ISSUE TITLE
Full title does not show up when viewing the issue

### ISSUE THREAD

**Issue by Zmanbaseball2** [thedillonb/CodeHub#57]
http://i.imgur.com/MEycCZ0.jpg
The title should go to the next line and not have a "...".
The only way to review the whole title is to edit the issue and edit the title.
2.2.1

**Comment by thedillonb** [comment]
The header has been modified in the next version. It is a little prettier and the text expands to it's full size

![ios simulator screen shot feb 7 2015 4 40 38 pm](https://cloud.githubusercontent.com/assets/1644068/6094078/11dcf15c-aee8-11e4-8e48-d3350dca2cbb.png)
