### ISSUE TITLE
iOS dark mode renders black text on dark background

### ISSUE THREAD

**Issue by haydenlewis** [thedillonb/CodeHub#669]
In the iOS app, the text is rendering in black on a dark background. This makes the text unreadable and the app unusable. I am using version 13.4.1. 

Thank you for this excellent app. Please let me know if I can provide any more information to help expedite this fix.

Screenshot: [Image](https://i.imgur.com/tKx6G6I.jpg)

**Comment by garrettw** [comment]
Duplicate of #667

**Comment by thedillonb** [comment]
Closing as duplicate. I will look to push out a fix this week.

**Comment by Cyber-Nexsus** [comment]
iOS 12.5.2 

Dark volumes
