### ISSUE TITLE
Dark mode has readability issues

### ISSUE THREAD

**Issue by synergiance** [thedillonb/CodeHub#685]
Before reading this, this is indeed a duplicate, please refer to the first posting of this issue, #667.

It seems that the dark mode support in this app is half baked, where if the device is in dark mode, parts of the app think the device is still in light mode, which is especially bad when you have dark text rendering on a dark background.

**Comment by garrettw** [comment]
Duplicate of #667 

Please look through existing issues before creating a new one.

**Comment by TheTechRobo** [comment]
Dupe of #684, #682, and #667. Please look in other issues (before posting one) to reduce clutter.

**Comment by synergiance** [comment]
As this is in fact a duplicate, and I’d rather people didn’t keep unnecessarily reiterating that fact, I’m closing this. Please read previous comments before commenting.
