### ISSUE TITLE
Text illegible in dark mode

### ISSUE THREAD

**Issue by dlidstrom** [thedillonb/CodeHub#687]
Titles and other text is barely visible.

**Comment by dlidstrom** [comment]
Oops duplicate

**Comment by TheTechRobo** [comment]
Dupe of #685, #684, #682, and #667. Please look through existing issues before you post one, to reduce clutter.

**Comment by dlidstrom** [comment]
It's only dupe of #667, and I closed it immediately.

**Comment by TheTechRobo** [comment]
I know, I was just saying.
