### ISSUE TITLE
Apple Dark Mode makes text unreadable

### ISSUE THREAD

**Issue by Hoidberg** [thedillonb/CodeHub#689]

**Comment by TheTechRobo** [comment]
Duplicate of #667. **Please** look through existing issues before submitting a new one, there have been too many issues repeating what was reported in May.

**Comment by ChristianPari** [comment]
Create automation
When "CodeHub" is open/closed
  -> Toggle "Appearance" 
This will toggle from dark to light for you as you switch back and forth from the app
