### ISSUE TITLE
[3.0 Redesign] Auto-hide various sections if you dont have access to them

### ISSUE THREAD

**Issue by Shawzborne** [thedillonb/CodeHub#81]
The Assigned, Milestone and Labels sections will be hidden if the Github user is not part of the repo.

**Comment by thedillonb** [comment]
Any user should still be able to see who the issue is assigned to and what milestone they anticipate a release.

**Comment by Shawzborne** [comment]
That's not exactly what I meant

**Comment by thedillonb** [comment]
Were you talking about when you create an issue? Then yeah, I added the functionaility to hide the fields you can't edit if you're not a collaborator.

(This is a repo I am not a collaborator)
![ios simulator screen shot feb 7 2015 10 42 31 pm](https://cloud.githubusercontent.com/assets/1644068/6095131/d942dbda-af1a-11e4-82c6-ac2e799398d7.png)

(This is a repo I am a collaborator)
![ios simulator screen shot feb 7 2015 10 42 44 pm](https://cloud.githubusercontent.com/assets/1644068/6095133/ddf2f746-af1a-11e4-91ea-7aacd6b43350.png)

**Comment by Shawzborne** [comment]
Yup that's what I meant :)

**Comment by Shawzborne** [comment]
Did you change your iMessage?

**Comment by thedillonb** [comment]
I actually have an Android as a primary phone now. My iPhone is just for dev now, and is Jailbroken, so I have a lot of the OS features disabled.

**Comment by Shawzborne** [comment]
Lol oh

**Comment by Shawzborne** [comment]
I sent you an email about adding me to the testflght beta, I'm not sure if your same email address still works. thanks
