### ISSUE TITLE
Centre the issue number (centre of vertical grey line)  

### ISSUE THREAD

**Issue by Shawzborne** [thedillonb/CodeHub#87]
Centre the issue number (centre of vertical grey line)  

![](http://i.imgur.com/sx2KDoK.jpg)

**Comment by thedillonb** [comment]
Issue number is aligned, vertically, as well as color-wise, with the issue title. Moving it vertically to align it with the center of the gray line ends up looking awkward as the eye, moving left to right, ends up looking at the issue state instead of naturally flowing into the title.
