### ISSUE TITLE
Replace default github repo icons with circle repo creator image

### ISSUE THREAD

**Issue by Shawzborne** [thedillonb/CodeHub#91]
![](http://i.imgur.com/qowewFf.jpg)

**Comment by thedillonb** [comment]
Good idea, will be in the next version:

![ios simulator screen shot feb 7 2015 3 26 31 pm](https://cloud.githubusercontent.com/assets/1644068/6093814/b5a272fe-aedd-11e4-9cff-d2f51bd2a406.png)
