### ISSUE TITLE
The text  randomly appears enlarged after clicking through

### ISSUE THREAD

**Issue by Shawzborne** [thedillonb/CodeHub#92]
The text  randomly appears enlarged after clicking through

![](http://i.imgur.com/6YFNvXQ.jpg)

![](http://i.imgur.com/u5xU61f.jpg)

**Comment by thedillonb** [comment]
Fixed in the upcoming 3.0 version. The viewport for all web-based GUI components should be pinned

```
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
```
