### ISSUE TITLE
Adding a collaborator shows the wrong person in news feed.

### ISSUE THREAD

**Issue by Whitetigerswt** [thedillonb/CodeHub#95]
If I added someone as a collaborator to my repo, in the news view, it would say "Whitetigerswt added as a collaborator to Whitetigerswt/my-repo".  What I mean is, it displays the person who ADDED a new collaborator as the new collaborator.

I'll attach 2 pictures, one will be how it looks on my iPhone, and the other one will be how it displays on github

iPhone:
![img_0124](https://cloud.githubusercontent.com/assets/1680233/3075397/c5575096-e374-11e3-8512-749fb7dac63d.PNG)

Github:
![88bfbc58f7fb10444fa69b3449266ba11](https://cloud.githubusercontent.com/assets/1680233/3075396/c556338c-e374-11e3-9819-1c9afe0ddaae.png)

As you can see, CodeHub displays the wrong collaborator.

**Comment by thedillonb** [comment]
This has been fixed in the upcoming verison (3.0):

![screen shot 2015-03-28 at 3 03 46 pm](https://cloud.githubusercontent.com/assets/1644068/6882455/b27d6b8e-d55b-11e4-959c-491fe6bed497.png)
