### ISSUE TITLE
Integration with 3rd party services.

### ISSUE THREAD

**Issue by DemonBob** [thedillonb/CodeHub#97]
Propose integrating app with select 3rd party services like trello (project management). Where we could like github issues/commits with card name/id's for trello. Or vise versa. 

Two or 3 of the most popular services would work, trello, jira, etc

**Comment by thedillonb** [comment]
I may come back to this later but for now the addition of 3rd party services within the application greatly adds to it's complexity and size. I'd definitely be open if somebody provided a PR with the functionaility.
